#!/usr/bin/env bash
# Extract production crates/pedradb-store/src/snapshot_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/snapshot-kernel \
  --src crates/pedradb-store/src/snapshot_kernel.rs \
  --base snapshot_kernel \
  --source-id snapshot "$@"
