#!/usr/bin/env bash
# Extract production crates/rocksdb-compat/src/iter_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/iter-kernel \
  --src crates/rocksdb-compat/src/iter_kernel.rs \
  --base iter_kernel \
  --source-id iter "$@"
