#!/usr/bin/env bash
# Extract production wal/crc.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/crc-kernel \
  --src crates/pedradb-core/src/wal/crc_kernel.rs \
  --base crc_kernel \
  --source-id crc "$@"
