#!/usr/bin/env bash
# Extract production wal/wal_state_kernel.rs via the shim crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/wal-state-kernel \
  --src crates/pedradb-core/src/wal/wal_state_kernel.rs \
  --base wal_state_kernel \
  --source-id wal_state "$@"
