#!/usr/bin/env bash
# Extract production crates/pedradb-core/src/lookup_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/lookup-kernel \
  --src crates/pedradb-core/src/lookup_kernel.rs \
  --base lookup_kernel \
  --source-id lookup "$@"
