#!/usr/bin/env bash
# Extract production wal/reopen_kernel.rs via the standalone crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/reopen-kernel \
  --src crates/pedradb-core/src/wal/reopen_kernel.rs \
  --base reopen_kernel \
  --source-id reopen "$@"
