#!/usr/bin/env bash
# Extract production crates/pedradb-replicate/src/ship_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/ship-kernel \
  --src crates/pedradb-replicate/src/ship_kernel.rs \
  --base ship_kernel \
  --source-id ship "$@"
