#!/usr/bin/env bash
# Extract production store commit_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/store-commit-kernel \
  --src crates/pedradb-store/src/commit_kernel.rs \
  --base store_commit_kernel \
  --source-id store_commit "$@"
