#!/usr/bin/env bash
# Extract production crates/pedradb-store/src/l28_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/l28-kernel \
  --src crates/pedradb-store/src/l28_kernel.rs \
  --base l28_kernel \
  --source-id l28 "$@"
