#!/usr/bin/env bash
# Extract production d1_modelo_kernel.rs via the shim crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/d1-modelo-kernel \
  --src crates/pedradb-core/src/d1_modelo_kernel.rs \
  --base d1_modelo_kernel \
  --source-id d1_modelo "$@"
