#!/usr/bin/env bash
# Extract production crates/pedradb-world/src/tcg_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/tcg-kernel \
  --src crates/pedradb-world/src/tcg_kernel.rs \
  --base tcg_kernel \
  --source-id tcg "$@"
