#!/usr/bin/env bash
# Extract production flush_kernel.rs (RFC-0174 P1.3).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/flush-kernel \
  --src crates/pedradb-core/src/flush_kernel.rs \
  --base flush_kernel \
  --source-id flush "$@"
