#!/usr/bin/env bash
# Extract production store ae_ack_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/store-ae-ack-kernel \
  --src crates/pedradb-store/src/ae_ack_kernel.rs \
  --base store_ae_ack_kernel \
  --source-id store_ae_ack "$@"
