#!/usr/bin/env bash
# Extract production crates/pedradb-store/src/compact_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/store-compact-kernel \
  --src crates/pedradb-store/src/compact_kernel.rs \
  --base store_compact_kernel \
  --source-id store_compact "$@"
