#!/usr/bin/env bash
# Extract production isolated_kernel.rs via the standalone crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/isolated-kernel \
  --src crates/pedradb-fold/src/isolated_kernel.rs \
  --base isolated_kernel \
  --source-id isolated "$@"
