#!/usr/bin/env bash
# Extract production group_commit_kernel.rs via the standalone crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/group-commit-kernel \
  --src crates/pedradb-core/src/group_commit_kernel.rs \
  --base group_commit_kernel \
  --source-id group_commit "$@"
