#!/usr/bin/env bash
# Extract production write_admission_kernel.rs (RFC-0170 P2.1).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/write-admission-kernel \
  --src crates/pedradb-core/src/write_admission_kernel.rs \
  --base write_admission_kernel \
  --source-id write_admission "$@"
