#!/usr/bin/env bash
# Extract production dcs apply_kernel.rs via the shim crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/dcs-apply-kernel \
  --src crates/pedradb-dcs/src/apply_kernel.rs \
  --base dcs_apply_kernel \
  --source-id dcs_apply "$@"
