#!/usr/bin/env bash
# Extract production commit_kernel.rs via the standalone crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/commit-kernel \
  --src crates/pedradb-raft/src/commit_kernel.rs \
  --base commit_kernel \
  --source-id commit "$@"
