#!/usr/bin/env bash
# Extract production env_crash_kernel.rs (+ group_commit_kernel.rs) via the shim crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/env-crash-kernel \
  --src crates/pedradb-core/src/env_crash_kernel.rs \
  --base env_crash_kernel \
  --source-id env_crash "$@"
