#!/usr/bin/env bash
# Extract production crates/pedradb-store/src/tx_glue_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/tx-glue-kernel \
  --src crates/pedradb-store/src/tx_glue_kernel.rs \
  --base tx_glue_kernel \
  --source-id tx_glue "$@"
