#!/usr/bin/env bash
# Extract production store apply_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/store-apply-kernel \
  --src crates/pedradb-store/src/apply_kernel.rs \
  --base store_apply_kernel \
  --source-id store_apply "$@"
