#!/usr/bin/env bash
# Extract production crates/pedradb-core/src/vlog_gc_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/vlog-gc-kernel \
  --src crates/pedradb-core/src/vlog_gc_kernel.rs \
  --base vlog_gc_kernel \
  --source-id vlog_gc "$@"
