#!/usr/bin/env bash
# Extract production crates/montanha-fdb-recipes/src/pack_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/pack-kernel \
  --src crates/montanha-fdb-recipes/src/pack_kernel.rs \
  --base pack_kernel \
  --source-id pack "$@"
