#!/usr/bin/env bash
# Extract production wal/recover_kernel.rs (+ wal/format.rs) via the shim crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/wal-recover-kernel \
  --src crates/pedradb-core/src/wal/recover_kernel.rs \
  --base wal_recover_kernel \
  --source-id wal_recover "$@"
