#!/usr/bin/env bash
# Extract production crates/pedradb-core/src/changelog_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/changelog-kernel \
  --src crates/pedradb-core/src/changelog_kernel.rs \
  --base changelog_kernel \
  --source-id changelog "$@"
