#!/usr/bin/env bash
# Extract production crates/pedradb-http/src/cl_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/cl-kernel \
  --src crates/pedradb-http/src/cl_kernel.rs \
  --base cl_kernel \
  --source-id cl "$@"
