#!/usr/bin/env bash
# Extract production crates/pedradb-journal/src/pin_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/pin-kernel \
  --src crates/pedradb-journal/src/pin_kernel.rs \
  --base pin_kernel \
  --source-id pin "$@"
