#!/usr/bin/env bash
# Extract production write_ack_kernel.rs via the shim crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/write-ack-kernel \
  --src crates/pedradb-core/src/write_ack_kernel.rs \
  --base write_ack_kernel \
  --source-id write_ack "$@"
