#!/usr/bin/env bash
# Extract production crates/pedradb-stream/src/cursor_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/cursor-kernel \
  --src crates/pedradb-stream/src/cursor_kernel.rs \
  --base cursor_kernel \
  --source-id cursor "$@"
