#!/usr/bin/env bash
# Extract production scale_kernel.rs (RFC-0176 P2.1). Does not measure µs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/scale-kernel \
  --src crates/pedradb-core/src/scale_kernel.rs \
  --base scale_kernel \
  --source-id scale "$@"
