#!/usr/bin/env bash
# Extract production crates/montanha-fdb-recipes/src/children_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/children-kernel \
  --src crates/montanha-fdb-recipes/src/children_kernel.rs \
  --base children_kernel \
  --source-id children "$@"
