#!/usr/bin/env bash
# Extract production crates/pedradb-spec/src/properties_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/properties-kernel \
  --src crates/pedradb-spec/src/properties_kernel.rs \
  --base properties_kernel \
  --source-id properties "$@"
