#!/usr/bin/env bash
# Extract production apply_kernel.rs via the standalone crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/apply-kernel \
  --src crates/pedradb-raft/src/apply_kernel.rs \
  --base apply_kernel \
  --source-id apply "$@"
