#!/usr/bin/env bash
# Extract production crates/pedradb-fold/src/fold_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/fold-kernel \
  --src crates/pedradb-fold/src/fold_kernel.rs \
  --base fold_kernel \
  --source-id fold "$@"
