#!/usr/bin/env bash
# Extract production crates/pedradb-store/src/index_val_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/index-val-kernel \
  --src crates/pedradb-store/src/index_val_kernel.rs \
  --base index_val_kernel \
  --source-id index_val "$@"
