#!/usr/bin/env bash
# Extract production crates/pedradb-core/src/manifest_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/manifest-kernel \
  --src crates/pedradb-core/src/manifest_kernel.rs \
  --base manifest_kernel \
  --source-id manifest "$@"
