#!/usr/bin/env bash
# Extract production ae_kernel.rs via the standalone crate.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/ae-kernel \
  --src crates/pedradb-raft/src/ae_kernel.rs \
  --base ae_kernel \
  --source-id ae "$@"
