#!/usr/bin/env bash
# Extract production crates/pedradb-store/src/rpc_mode_kernel.rs.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/rpc-mode-kernel \
  --src crates/pedradb-store/src/rpc_mode_kernel.rs \
  --base rpc_mode_kernel \
  --source-id rpc_mode "$@"
