#!/usr/bin/env bash
# Extract production prefix.rs via the standalone crate (RFC-0170 P0.3).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/prefix-kernel \
  --src crates/pedradb-core/src/prefix_kernel.rs \
  --base prefix_kernel \
  --source-id prefix "$@"
