#!/usr/bin/env bash
# Extract production disk_pressure_kernel.rs (RFC-0179).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" aeneas \
  --crate formal/aeneas/disk-pressure-kernel \
  --src crates/pedradb-core/src/disk_pressure_kernel.rs \
  --base disk_pressure_kernel \
  --source-id disk_pressure "$@"
