#!/usr/bin/env bash
# Check the Lean theorems over the Aeneas extract of bloom.rs (RFC-0030).
# Requires elan toolchain leanprover/lean4:v4.31.0 (see formal/aeneas/PINS.md).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" lean \
  --main Bloom \
  --build "Bloom" "$@"
