#!/usr/bin/env bash
# Machine-check first_probe_on_equal_lo on the file rustc links
# (single artifact — not the twin-cópia). Slice covering walk stays rustc.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-core/src/probe_order_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
