#!/usr/bin/env bash
# Machine-check the flush-pipeline decision kernel (RFC-0056 P0.2).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-core/src/flush_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
