#!/usr/bin/env bash
# Machine-check dcs_apply_should_advance on the file rustc links
# (single artifact — not the twin-cópia). RFC-0002 P12 / F12 / F22.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-dcs/src/apply_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
