#!/usr/bin/env bash
# Machine-check changelog SST-rebuild gate on the file rustc links
# (single artifact — not the twin-cópia). RFC-0002 P22 / F53.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-core/src/changelog_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
