#!/usr/bin/env bash
# Machine-check journal pin rules on the file rustc links
# (single artifact — not the twin-cópia). Slipstream H1 / F54 cousin.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-journal/src/pin_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
