#!/usr/bin/env bash
# Machine-check stream cursor on the file rustc links
# (single artifact — not the twin-cópia). RFC-0002 P20 / F54.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-stream/src/cursor_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
