#!/usr/bin/env bash
# Machine-check crc_match_ok on the file rustc links (single artifact —
# not the twin-cópia). Not a collision theorem (P2.2 / R-crc).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-core/src/wal/crc_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
