#!/usr/bin/env bash
# Machine-check F62 pack injectivity on the file rustc links
# (single artifact — not the twin-cópia). RFC-0002 P25.
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/montanha-fdb-recipes/src/pack_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
