#!/usr/bin/env bash
# Machine-check c_len_admitted on the file rustc links (single artifact —
# not the twin-cópia). Not a free-table proof (P2.2).
# Generated by scripts/gen_proof_shims.py — the logic lives in scripts/proof.sh.
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/crates/pedradb-capi/src/handles_kernel.rs"
exec "$(cd "$(dirname "$0")" && pwd)/proof.sh" verus "$SRC" "$@"
