-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_apply_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedra_aeneas_apply_kernel

/-- [pedra_aeneas_apply_kernel::ApplyAction]
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 25:0-34:1
    Visibility: public -/
@[discriminant isize]
inductive ApplyAction where
| Done : ApplyAction
| Stop : ApplyAction
| Apply : ApplyAction

/-- [pedra_aeneas_apply_kernel::{impl core::fmt::Debug for pedra_aeneas_apply_kernel::ApplyAction}::fmt]:
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:9-24:14
    Visibility: public -/
def ApplyAction.Insts.CoreFmtDebug.fmt
  (self : ApplyAction) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | ApplyAction.Done => core.fmt.Formatter.write_str f (toStr "Done")
  | ApplyAction.Stop => core.fmt.Formatter.write_str f (toStr "Stop")
  | ApplyAction.Apply => core.fmt.Formatter.write_str f (toStr "Apply")

/-- Trait implementation: [pedra_aeneas_apply_kernel::{impl core::fmt::Debug for pedra_aeneas_apply_kernel::ApplyAction}]
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:9-24:14 -/
@[reducible]
def ApplyAction.Insts.CoreFmtDebug : core.fmt.Debug ApplyAction := {
  fmt := ApplyAction.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_apply_kernel::{impl core::clone::Clone for pedra_aeneas_apply_kernel::ApplyAction}::clone]:
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:16-24:21
    Visibility: public -/
def ApplyAction.Insts.CoreCloneClone.clone
  (self : ApplyAction) : Result ApplyAction := do
  ok self

/-- Trait implementation: [pedra_aeneas_apply_kernel::{impl core::clone::Clone for pedra_aeneas_apply_kernel::ApplyAction}]
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:16-24:21 -/
@[reducible]
def ApplyAction.Insts.CoreCloneClone : core.clone.Clone ApplyAction := {
  clone := ApplyAction.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pedra_aeneas_apply_kernel::{impl core::marker::Copy for pedra_aeneas_apply_kernel::ApplyAction}]
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:23-24:27 -/
@[reducible]
def ApplyAction.Insts.CoreMarkerCopy : core.marker.Copy ApplyAction := {
  cloneInst := ApplyAction.Insts.CoreCloneClone
}

/-- Trait implementation: [pedra_aeneas_apply_kernel::{impl core::marker::StructuralPartialEq for pedra_aeneas_apply_kernel::ApplyAction}]
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:29-24:38 -/
@[reducible]
def ApplyAction.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ApplyAction := {
}

/-- [pedra_aeneas_apply_kernel::{impl core::cmp::PartialEq<pedra_aeneas_apply_kernel::ApplyAction> for pedra_aeneas_apply_kernel::ApplyAction}::eq]:
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:29-24:38
    Visibility: public -/
def ApplyAction.Insts.CoreCmpPartialEqApplyAction.eq
  (self : ApplyAction) (other : ApplyAction) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [pedra_aeneas_apply_kernel::{impl core::cmp::PartialEq<pedra_aeneas_apply_kernel::ApplyAction> for pedra_aeneas_apply_kernel::ApplyAction}]
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:29-24:38 -/
@[reducible]
def ApplyAction.Insts.CoreCmpPartialEqApplyAction : core.cmp.PartialEq
  ApplyAction ApplyAction := {
  eq := ApplyAction.Insts.CoreCmpPartialEqApplyAction.eq
}

/-- [pedra_aeneas_apply_kernel::{impl core::cmp::Eq for pedra_aeneas_apply_kernel::ApplyAction}::assert_fields_are_eq]:
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:40-24:42
    Visibility: public -/
def ApplyAction.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ApplyAction) : Result Unit := do
  ok ()

/-- Trait implementation: [pedra_aeneas_apply_kernel::{impl core::cmp::Eq for pedra_aeneas_apply_kernel::ApplyAction}]
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 24:40-24:42 -/
@[reducible]
def ApplyAction.Insts.CoreCmpEq : core.cmp.Eq ApplyAction := {
  partialEqInst := ApplyAction.Insts.CoreCmpPartialEqApplyAction
  assert_fields_are_eq := ApplyAction.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_apply_kernel::apply_advance]:
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 51:0-59:1
    Visibility: public -/
def apply_advance
  (last_applied : Std.U64) (commit_index : Std.U64) (entry_present : Bool) :
  Result ApplyAction
  := do
  if last_applied >= commit_index
  then ok ApplyAction.Done
  else if entry_present
       then ok ApplyAction.Apply
       else ok ApplyAction.Stop

/-- [pedra_aeneas_apply_kernel::apply_advance_as_is_skip_holes]:
    Source: '../../../crates/pedradb-raft/src/apply_kernel.rs', lines 65:0-75:1
    Visibility: public -/
def apply_advance_as_is_skip_holes
  (last_applied : Std.U64) (commit_index : Std.U64) (_entry_present : Bool) :
  Result ApplyAction
  := do
  if last_applied >= commit_index
  then ok ApplyAction.Done
  else ok ApplyAction.Apply

end pedra_aeneas_apply_kernel
