-- AUTO-GENERATED by scripts/ratchet/derive_count_annotations.py
-- RFC-0204 P1.1 — retired mirror: the Nat count-twin layer of the
-- memtable→flush amortization credit is MACHINE-EMITTED from the
-- declared twin shape, validated against the same parse that derives
-- step_work (anchor def still present in the extract; emitted theorem
-- name equals the registered count row). DO NOT EDIT: regenerate with
--   python3 scripts/ratchet/derive_count_annotations.py
-- (scripts/lean_extracts.sh gates on --check before building). The
-- semantic bridges to the real extract stay HUMAN, by design, in
-- FlushAmortBridges.lean.
import Aeneas
import FlushKernel
open Aeneas Aeneas.Std Result
open pedra_aeneas_flush_kernel

/-! ## Count twin (pure Nat, machine-emitted) -/

inductive FlushStep
  | write (units : Nat)
  | tick

/-- Gate twin of `auto_flush_due`: a tick fires exactly when the
memtable has reached the limit (the armed policy). -/
def should_flush (limit m : Nat) : Bool := decide (limit ≤ m)

/-- Work twin of the memtable→flush cycle: returns
(final memtable bytes, total flushed bytes). A firing tick pays the
current memtable and resets it to zero. -/
def run_flush_steps (limit : Nat) : List FlushStep → Nat → Nat × Nat
  | [], m => (m, 0)
  | FlushStep.write u :: rest, m => run_flush_steps limit rest (m + u)
  | FlushStep.tick :: rest, m =>
      if should_flush limit m then
        let p := run_flush_steps limit rest 0
        (p.1, m + p.2)
      else run_flush_steps limit rest m

/-- Total units handed to the memtable by the schedule. -/
def write_units : List FlushStep → Nat
  | [] => 0
  | FlushStep.write u :: rest => u + write_units rest
  | FlushStep.tick :: rest => write_units rest

/-- Gate twin sharpness: a non-firing check certifies the memtable is
still under the limit. -/
theorem should_flush_false_under_limit : ∀ (limit m : Nat),
    should_flush limit m = false → m < limit := by
  intro limit m h
  unfold should_flush at h
  simp only [decide_eq_false_iff_not, Nat.not_le] at h
  exact h

/-- Accounting invariant: every byte is either still in the memtable
or was flushed exactly once — never both, never neither. -/
theorem run_paid_plus_mem_le : ∀ (limit : Nat) (steps : List FlushStep) (m : Nat),
    (run_flush_steps limit steps m).2 + (run_flush_steps limit steps m).1
      ≤ write_units steps + m := by
  intro limit steps
  induction steps with
  | nil => intro m; simp [run_flush_steps]
  | cons step rest ih =>
    intro m
    cases step with
    | write u =>
        have h := ih (m + u)
        simp only [run_flush_steps, write_units] at h ⊢
        omega
    | tick =>
        simp only [run_flush_steps, write_units]
        split
        · next _hfired =>
            have h0 := ih 0
            dsimp only
            omega
        · next _ =>
            exact ih m

/-- RFC-0199 count (P1.2), machine-emitted since RFC-0204 P1.1: the
flush work a schedule pays never exceeds the bytes it wrote plus the
memtable's initial fill — k writes under the cap amortize their
flushes to a constant independent of the level structure below it. -/
theorem memtable_flush_amortized : ∀ (limit : Nat) (steps : List FlushStep) (m : Nat),
    (run_flush_steps limit steps m).2 ≤ write_units steps + m := by
  intro limit steps m
  have h := run_paid_plus_mem_le limit steps m
  omega
