-- AUTO-GENERATED by scripts/ratchet/derive_count_annotations.py
-- RFC-0204 P1.2 — retired mirror: the Nat count-twin layer of the
-- bloom probe walk is MACHINE-EMITTED from the declared twin shape,
-- validated against the same parse that derives step_work (anchor
-- def still present in the extract; emitted theorem name equals the
-- registered count row). DO NOT EDIT: regenerate with
--   python3 scripts/ratchet/derive_count_annotations.py
-- (scripts/lean_extracts.sh gates on --check before building). The
-- semantic bridges to the real extract stay HUMAN, by design, in
-- BloomBridges.lean.
import Aeneas
import BloomKernel
open Aeneas Aeneas.Std Result ControlFlow
open pedra_aeneas_bloom_kernel

/-! ## Count twin (pure Nat, machine-emitted) -/

/-- Work twin of the probe loop: iterations while `remaining` probes
are left (the loop's own decreasing measure `k - i`) — one step per
probe. -/
def bloom_probe_steps : Nat → Nat
  | 0 => 0
  | remaining + 1 => 1 + bloom_probe_steps remaining

/-- Inner twin bound: one iteration per remaining probe, no more. -/
theorem bloom_probe_steps_le : ∀ (remaining : Nat),
    bloom_probe_steps remaining ≤ remaining := by
  intro remaining
  induction remaining with
  | zero => simp [bloom_probe_steps]
  | succ d ih => simp only [bloom_probe_steps]; omega

/-- RFC-0199 count (P2.3), machine-emitted since RFC-0204 P1.2: a
bloom query's work twin never exceeds the policy's probe count k — at
most one bit test per probe per query; the short-circuit (clear bit ⇒
`done false`) only ever pays LESS than the full pass. -/
theorem bloom_may_contain_work_bound : ∀ (k : Nat),
    bloom_probe_steps k ≤ k := by
  intro k
  exact bloom_probe_steps_le k
