-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_capi_handles_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedra_aeneas_capi_handles_kernel

/-- [pedra_aeneas_capi_handles_kernel::c_len_admitted]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 48:0-50:1
    Visibility: public -/
def c_len_admitted (len : Std.Usize) (max : Std.Usize) : Result Bool := do
  ok (len <= max)

/-- [pedra_aeneas_capi_handles_kernel::c_len_admitted_as_is]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 55:0-57:1
    Visibility: public -/
def c_len_admitted_as_is
  (_len : Std.Usize) (_max : Std.Usize) : Result Bool := do
  ok true

/-- [pedra_aeneas_capi_handles_kernel::C_PATH_WALK_BYTES]
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 99:0-99:42
    Visibility: public -/
@[global_simps, irreducible] def C_PATH_WALK_BYTES : Std.Usize := 4096#usize

/-- [pedra_aeneas_capi_handles_kernel::c_path_walk_bytes]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 104:0-106:1
    Visibility: public -/
def c_path_walk_bytes : Result Std.Usize := do
  ok C_PATH_WALK_BYTES

/-- [pedra_aeneas_capi_handles_kernel::c_path_walk_bytes_as_is]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 110:0-112:1
    Visibility: public -/
def c_path_walk_bytes_as_is : Result Std.Usize := do
  ok core.num.Usize.MAX

/-- [pedra_aeneas_capi_handles_kernel::c_path_nul_off_admitted]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 117:0-119:1
    Visibility: public -/
def c_path_nul_off_admitted (n : Std.Usize) : Result Bool := do
  let i ← c_path_walk_bytes
  ok (n < i)

/-- [pedra_aeneas_capi_handles_kernel::c_path_nul_off_admitted_as_is]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 123:0-125:1
    Visibility: public -/
def c_path_nul_off_admitted_as_is (_n : Std.Usize) : Result Bool := do
  ok true

/-- [pedra_aeneas_capi_handles_kernel::c_free_table_admitted]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 131:0-133:1
    Visibility: public -/
def c_free_table_admitted : Result Bool := do
  ok false

/-- [pedra_aeneas_capi_handles_kernel::c_free_table_admitted_as_is]:
    Source: '../../../crates/pedradb-capi/src/handles.rs', lines 137:0-139:1
    Visibility: public -/
def c_free_table_admitted_as_is : Result Bool := do
  ok true

end pedra_aeneas_capi_handles_kernel
