-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_children_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pedra_aeneas_children_kernel

/-- [core::cmp::impls::{impl core::cmp::PartialOrd<&'_0 B> for &'_1 A}::lt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2141:8-2141:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::cmp::impls::{impl core::cmp::PartialOrd<&'_0 B> for &'_1 A}::ge]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2153:8-2153:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::ge]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::ge"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.ge
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialEq<[U]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 14:0-16:28
    Name pattern: [core::cmp::PartialEq<[@T], [@U]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T], [@U]>"]
def Slice.Insts.CoreCmpPartialEqSlice {T : Type} {U : Type} (cmpPartialEqInst :
  core.cmp.PartialEq T U) : core.cmp.PartialEq (Slice T) (Slice U) := {
  eq := core.slice.cmp.PartialEqSlice.eq cmpPartialEqInst
}

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::ge]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 84:4-84:38
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::ge]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::ge"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.ge
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result Bool

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::lt]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 64:4-64:38
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::lt]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::lt"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.lt
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result Bool

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::partial_cmp]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 60:4-60:58
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::partial_cmp"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.partial_cmp
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result (Option Ordering)

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 58:0-58:52
    Name pattern: [core::cmp::PartialOrd<[@T], [@T]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialOrd<[@T], [@T]>"]
def Slice.Insts.CoreCmpPartialOrdSlice {T : Type} (cmpPartialOrdInst :
  core.cmp.PartialOrd T T) : core.cmp.PartialOrd (Slice T) (Slice T) := {
  partialEqInst := Slice.Insts.CoreCmpPartialEqSlice
    cmpPartialOrdInst.partialEqInst
  partial_cmp := Slice.Insts.CoreCmpPartialOrdSlice.partial_cmp
    cmpPartialOrdInst
  lt := Slice.Insts.CoreCmpPartialOrdSlice.lt cmpPartialOrdInst
  ge := Slice.Insts.CoreCmpPartialOrdSlice.ge cmpPartialOrdInst
}

/-- [pedra_aeneas_children_kernel::PACKED_CHILD_SEP]
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 16:0-16:38
    Visibility: public -/
@[global_simps, irreducible] def PACKED_CHILD_SEP : Std.U8 := 0#u8

/-- [pedra_aeneas_children_kernel::PACKED_CHILD_END]
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 18:0-18:38
    Visibility: public -/
@[global_simps, irreducible] def PACKED_CHILD_END : Std.U8 := 1#u8

/-- [pedra_aeneas_children_kernel::PACKED_CHILD_END_AS_IS]
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 20:0-20:44
    Visibility: public -/
@[global_simps, irreducible] def PACKED_CHILD_END_AS_IS : Std.U8 := 255#u8

/-- [pedra_aeneas_children_kernel::packed_children_start]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 24:0-28:1
    Visibility: public -/
def packed_children_start
  (packed : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let s ← alloc.slice.Slice.to_vec core.clone.CloneU8 packed
  alloc.vec.Vec.push s PACKED_CHILD_SEP

/-- [pedra_aeneas_children_kernel::packed_children_start_as_is]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 32:0-34:1
    Visibility: public -/
def packed_children_start_as_is
  (packed : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  alloc.slice.Slice.to_vec core.clone.CloneU8 packed

/-- [pedra_aeneas_children_kernel::packed_children_end]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 38:0-42:1
    Visibility: public -/
def packed_children_end
  (packed : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let e ← alloc.slice.Slice.to_vec core.clone.CloneU8 packed
  alloc.vec.Vec.push e PACKED_CHILD_END

/-- [pedra_aeneas_children_kernel::packed_children_end_as_is]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 47:0-51:1
    Visibility: public -/
def packed_children_end_as_is
  (packed : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let e ← alloc.slice.Slice.to_vec core.clone.CloneU8 packed
  alloc.vec.Vec.push e PACKED_CHILD_END_AS_IS

/-- [pedra_aeneas_children_kernel::key_in_half_open]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 55:0-57:1
    Visibility: public -/
def key_in_half_open
  (key : Slice Std.U8) (start : Slice Std.U8) (end1 : Slice Std.U8) :
  Result Bool
  := do
  let b ←
    Shared1A.Insts.CoreCmpPartialOrdShared0B.ge
      (Slice.Insts.CoreCmpPartialOrdSlice core.cmp.PartialOrdU8) key start
  if b
  then
    Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
      (Slice.Insts.CoreCmpPartialOrdSlice core.cmp.PartialOrdU8) key end1
  else ok false

/-- [pedra_aeneas_children_kernel::key_in_half_open_as_is]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 61:0-63:1
    Visibility: public -/
def key_in_half_open_as_is
  (key : Slice Std.U8) (start : Slice Std.U8) (end1 : Slice Std.U8) :
  Result Bool
  := do
  Shared1A.Insts.CoreCmpPartialOrdShared0B.ge
    (Slice.Insts.CoreCmpPartialOrdSlice core.cmp.PartialOrdU8) key start

/-- [pedra_aeneas_children_kernel::next_byte_in_packed_children]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 67:0-69:1
    Visibility: public -/
def next_byte_in_packed_children (next : Std.U8) : Result Bool := do
  ok (next = PACKED_CHILD_SEP)

/-- [pedra_aeneas_children_kernel::next_byte_in_packed_children_as_is]:
    Source: '../../../crates/distributed-fdb-recipes/src/children_kernel.rs', lines 73:0-75:1
    Visibility: public -/
def next_byte_in_packed_children_as_is (next : Std.U8) : Result Bool := do
  ok (next < PACKED_CHILD_END_AS_IS)

end pedra_aeneas_children_kernel
