-- AUTO-GENERATED by scripts/ratchet/derive_count_annotations.py
-- RFC-0199 P2.1 — mechanically derived per-step cost annotations
-- over the Aeneas extracts. DO NOT EDIT: regenerate with
--   python3 scripts/ratchet/derive_count_annotations.py
-- (scripts/lean_extracts.sh gates on --check before building).
-- step_work = leaf_calls (in-file axioms) + local_calls (in-file
-- defs) + dispatches (match/if) + cmp_ops + arith_ops; nested
-- enrolled-loop calls and self-recursion are counted separately
-- and EXCLUDED — a sub-loop is charged by its own registered
-- count theorem, never folded into a flat constant.
import FlushKernel
import ScanKernel
import LsmR1Kernel
import ProbeOrderKernel
import ScaleKernel

namespace pedra_aeneas_count_derived

/-- `auto_flush_due` (FlushKernel.lean, catalog:auto_flush_due): derived one-unfolding
     cost — leaf=0 local=0 dispatch=1
     cmp=1 arith=0 (nested=0,
     self=0 excluded). AUTO-GENERATED. -/
def auto_flush_due_leaf_calls : Nat := 0
def auto_flush_due_local_calls : Nat := 0
def auto_flush_due_dispatches : Nat := 1
def auto_flush_due_cmp_ops : Nat := 1
def auto_flush_due_arith_ops : Nat := 0
def auto_flush_due_nested_calls : Nat := 0
def auto_flush_due_self_calls : Nat := 0
def auto_flush_due_step_work : Nat := 2
theorem auto_flush_due_step_work_eq : auto_flush_due_step_work = auto_flush_due_leaf_calls + auto_flush_due_local_calls + auto_flush_due_dispatches + auto_flush_due_cmp_ops + auto_flush_due_arith_ops := by rfl
theorem auto_flush_due_step_work_positive : 0 < auto_flush_due_step_work := by decide

/-- `scan_kernel.scan_reads_file` (ScanKernel.lean, catalog:scan_guard): derived one-unfolding
     cost — leaf=1 local=2 dispatch=1
     cmp=0 arith=0 (nested=0,
     self=0 excluded). AUTO-GENERATED. -/
def scan_kernel_scan_reads_file_leaf_calls : Nat := 1
def scan_kernel_scan_reads_file_local_calls : Nat := 2
def scan_kernel_scan_reads_file_dispatches : Nat := 1
def scan_kernel_scan_reads_file_cmp_ops : Nat := 0
def scan_kernel_scan_reads_file_arith_ops : Nat := 0
def scan_kernel_scan_reads_file_nested_calls : Nat := 0
def scan_kernel_scan_reads_file_self_calls : Nat := 0
def scan_kernel_scan_reads_file_step_work : Nat := 4
theorem scan_kernel_scan_reads_file_step_work_eq : scan_kernel_scan_reads_file_step_work = scan_kernel_scan_reads_file_leaf_calls + scan_kernel_scan_reads_file_local_calls + scan_kernel_scan_reads_file_dispatches + scan_kernel_scan_reads_file_cmp_ops + scan_kernel_scan_reads_file_arith_ops := by rfl
theorem scan_kernel_scan_reads_file_step_work_positive : 0 < scan_kernel_scan_reads_file_step_work := by decide

/-- `lsm_compact_src_loop` (LsmR1Kernel.lean, catalog:lsm_compact): derived one-unfolding
     cost — leaf=0 local=1 dispatch=2
     cmp=1 arith=1 (nested=1,
     self=0 excluded). AUTO-GENERATED. -/
def lsm_compact_src_loop_leaf_calls : Nat := 0
def lsm_compact_src_loop_local_calls : Nat := 1
def lsm_compact_src_loop_dispatches : Nat := 2
def lsm_compact_src_loop_cmp_ops : Nat := 1
def lsm_compact_src_loop_arith_ops : Nat := 1
def lsm_compact_src_loop_nested_calls : Nat := 1
def lsm_compact_src_loop_self_calls : Nat := 0
def lsm_compact_src_loop_step_work : Nat := 5
theorem lsm_compact_src_loop_step_work_eq : lsm_compact_src_loop_step_work = lsm_compact_src_loop_leaf_calls + lsm_compact_src_loop_local_calls + lsm_compact_src_loop_dispatches + lsm_compact_src_loop_cmp_ops + lsm_compact_src_loop_arith_ops := by rfl
theorem lsm_compact_src_loop_step_work_positive : 0 < lsm_compact_src_loop_step_work := by decide

/-- `lsm_compact_inner_loop` (LsmR1Kernel.lean, catalog:lsm_compact): derived one-unfolding
     cost — leaf=0 local=2 dispatch=3
     cmp=2 arith=3 (nested=0,
     self=0 excluded). AUTO-GENERATED. -/
def lsm_compact_inner_loop_leaf_calls : Nat := 0
def lsm_compact_inner_loop_local_calls : Nat := 2
def lsm_compact_inner_loop_dispatches : Nat := 3
def lsm_compact_inner_loop_cmp_ops : Nat := 2
def lsm_compact_inner_loop_arith_ops : Nat := 3
def lsm_compact_inner_loop_nested_calls : Nat := 0
def lsm_compact_inner_loop_self_calls : Nat := 0
def lsm_compact_inner_loop_step_work : Nat := 10
theorem lsm_compact_inner_loop_step_work_eq : lsm_compact_inner_loop_step_work = lsm_compact_inner_loop_leaf_calls + lsm_compact_inner_loop_local_calls + lsm_compact_inner_loop_dispatches + lsm_compact_inner_loop_cmp_ops + lsm_compact_inner_loop_arith_ops := by rfl
theorem lsm_compact_inner_loop_step_work_positive : 0 < lsm_compact_inner_loop_step_work := by decide

/-- `probe_order_covering_loop` (ProbeOrderKernel.lean, catalog:probe_order_covering): derived one-unfolding
     cost — leaf=0 local=2 dispatch=4
     cmp=3 arith=4 (nested=0,
     self=0 excluded). AUTO-GENERATED. -/
def probe_order_covering_loop_leaf_calls : Nat := 0
def probe_order_covering_loop_local_calls : Nat := 2
def probe_order_covering_loop_dispatches : Nat := 4
def probe_order_covering_loop_cmp_ops : Nat := 3
def probe_order_covering_loop_arith_ops : Nat := 4
def probe_order_covering_loop_nested_calls : Nat := 0
def probe_order_covering_loop_self_calls : Nat := 0
def probe_order_covering_loop_step_work : Nat := 13
theorem probe_order_covering_loop_step_work_eq : probe_order_covering_loop_step_work = probe_order_covering_loop_leaf_calls + probe_order_covering_loop_local_calls + probe_order_covering_loop_dispatches + probe_order_covering_loop_cmp_ops + probe_order_covering_loop_arith_ops := by rfl
theorem probe_order_covering_loop_step_work_positive : 0 < probe_order_covering_loop_step_work := by decide

/-- `level_count_loop` (ScaleKernel.lean, catalog:scale_predict): derived one-unfolding
     cost — leaf=1 local=0 dispatch=2
     cmp=2 arith=0 (nested=0,
     self=0 excluded). AUTO-GENERATED. -/
def level_count_loop_leaf_calls : Nat := 1
def level_count_loop_local_calls : Nat := 0
def level_count_loop_dispatches : Nat := 2
def level_count_loop_cmp_ops : Nat := 2
def level_count_loop_arith_ops : Nat := 0
def level_count_loop_nested_calls : Nat := 0
def level_count_loop_self_calls : Nat := 0
def level_count_loop_step_work : Nat := 5
theorem level_count_loop_step_work_eq : level_count_loop_step_work = level_count_loop_leaf_calls + level_count_loop_local_calls + level_count_loop_dispatches + level_count_loop_cmp_ops + level_count_loop_arith_ops := by rfl
theorem level_count_loop_step_work_positive : 0 < level_count_loop_step_work := by decide

/-- Every enrolled extract function does at least one unit of
     mechanically counted work per unfolding. -/
theorem all_enrolled_step_work_positive : 0 < auto_flush_due_step_work + scan_kernel_scan_reads_file_step_work + lsm_compact_src_loop_step_work + lsm_compact_inner_loop_step_work + probe_order_covering_loop_step_work + level_count_loop_step_work := by decide

end pedra_aeneas_count_derived
