-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_group_commit_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedra_aeneas_group_commit_kernel

/-- [pedra_aeneas_group_commit_kernel::occ_conflict]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 51:0-53:1
    Visibility: public -/
def occ_conflict
  (snap : Std.U64) (last_seq : Std.U64) (touched_key_written_after : Bool) :
  Result Bool
  := do
  if last_seq > snap
  then ok touched_key_written_after
  else ok false

/-- [pedra_aeneas_group_commit_kernel::OccRead]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 58:0-64:1
    Visibility: public -/
structure OccRead where
  snap : Std.U64
  touched_key_written_after : Bool

/-- [pedra_aeneas_group_commit_kernel::{impl core::fmt::Debug for pedra_aeneas_group_commit_kernel::OccRead}::fmt]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:9-57:14
    Visibility: public -/
def OccRead.Insts.CoreFmtDebug.fmt
  (self : OccRead) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.snap
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool)
      self.touched_key_written_after
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "OccRead") (toStr
    "snap") dyn (toStr "touched_key_written_after") dyn1

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::fmt::Debug for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:9-57:14 -/
@[reducible]
def OccRead.Insts.CoreFmtDebug : core.fmt.Debug OccRead := {
  fmt := OccRead.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::clone::Clone for pedra_aeneas_group_commit_kernel::OccRead}::clone]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:16-57:21
    Visibility: public -/
def OccRead.Insts.CoreCloneClone.clone (self : OccRead) : Result OccRead := do
  ok self

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::clone::Clone for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:16-57:21 -/
@[reducible]
def OccRead.Insts.CoreCloneClone : core.clone.Clone OccRead := {
  clone := OccRead.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::marker::Copy for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:23-57:27 -/
@[reducible]
def OccRead.Insts.CoreMarkerCopy : core.marker.Copy OccRead := {
  cloneInst := OccRead.Insts.CoreCloneClone
}

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::marker::StructuralPartialEq for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:29-57:38 -/
@[reducible]
def OccRead.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq OccRead := {
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::cmp::PartialEq<pedra_aeneas_group_commit_kernel::OccRead> for pedra_aeneas_group_commit_kernel::OccRead}::eq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:29-57:38
    Visibility: public -/
def OccRead.Insts.CoreCmpPartialEqOccRead.eq
  (self : OccRead) (other : OccRead) : Result Bool := do
  if self.snap = other.snap
  then ok (self.touched_key_written_after = other.touched_key_written_after)
  else ok false

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::cmp::PartialEq<pedra_aeneas_group_commit_kernel::OccRead> for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:29-57:38 -/
@[reducible]
def OccRead.Insts.CoreCmpPartialEqOccRead : core.cmp.PartialEq OccRead OccRead
  := {
  eq := OccRead.Insts.CoreCmpPartialEqOccRead.eq
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::cmp::Eq for pedra_aeneas_group_commit_kernel::OccRead}::assert_fields_are_eq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:40-57:42
    Visibility: public -/
def OccRead.Insts.CoreCmpEq.assert_fields_are_eq
  (self : OccRead) : Result Unit := do
  ok ()

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::cmp::Eq for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:40-57:42 -/
@[reducible]
def OccRead.Insts.CoreCmpEq : core.cmp.Eq OccRead := {
  partialEqInst := OccRead.Insts.CoreCmpPartialEqOccRead
  assert_fields_are_eq := OccRead.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_group_commit_kernel::group_validate]: loop body 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 74:4-81:5
    Visibility: public -/
@[rust_loop_body]
def group_validate_loop.body
  (reads : Slice OccRead) (last_seq : Std.U64) (out : alloc.vec.Vec Bool)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Bool) × Std.Usize) (alloc.vec.Vec Bool))
  := do
  let i1 := Slice.len reads
  if i < i1
  then
    let or ← Slice.index_usize reads i
    let b ← occ_conflict or.snap last_seq or.touched_key_written_after
    let out1 ← alloc.vec.Vec.push out b
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [pedra_aeneas_group_commit_kernel::group_validate]: loop 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 74:4-81:5
    Visibility: public -/
@[rust_loop]
def group_validate_loop
  (reads : Slice OccRead) (last_seq : Std.U64) (out : alloc.vec.Vec Bool)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Bool)
  := do
  loop
    (fun (out1, i1) => group_validate_loop.body reads last_seq out1 i1)
    (out, i)

/-- [pedra_aeneas_group_commit_kernel::group_validate]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 71:0-83:1
    Visibility: public -/
def group_validate
  (reads : Slice OccRead) (last_seq : Std.U64) :
  Result (alloc.vec.Vec Bool)
  := do
  let i := Slice.len reads
  let out := alloc.vec.Vec.with_capacity Bool i
  group_validate_loop reads last_seq out 0#usize

/-- [pedra_aeneas_group_commit_kernel::OccMemberFate]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 88:0-95:1
    Visibility: public -/
@[discriminant isize]
inductive OccMemberFate where
| Ok : OccMemberFate
| TooOld : OccMemberFate
| Conflict : OccMemberFate

/-- [pedra_aeneas_group_commit_kernel::{impl core::fmt::Debug for pedra_aeneas_group_commit_kernel::OccMemberFate}::fmt]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:9-87:14
    Visibility: public -/
def OccMemberFate.Insts.CoreFmtDebug.fmt
  (self : OccMemberFate) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | OccMemberFate.Ok => core.fmt.Formatter.write_str f (toStr "Ok")
  | OccMemberFate.TooOld => core.fmt.Formatter.write_str f (toStr "TooOld")
  | OccMemberFate.Conflict => core.fmt.Formatter.write_str f (toStr "Conflict")

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::fmt::Debug for pedra_aeneas_group_commit_kernel::OccMemberFate}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:9-87:14 -/
@[reducible]
def OccMemberFate.Insts.CoreFmtDebug : core.fmt.Debug OccMemberFate := {
  fmt := OccMemberFate.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::clone::Clone for pedra_aeneas_group_commit_kernel::OccMemberFate}::clone]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:16-87:21
    Visibility: public -/
def OccMemberFate.Insts.CoreCloneClone.clone
  (self : OccMemberFate) : Result OccMemberFate := do
  ok self

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::clone::Clone for pedra_aeneas_group_commit_kernel::OccMemberFate}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:16-87:21 -/
@[reducible]
def OccMemberFate.Insts.CoreCloneClone : core.clone.Clone OccMemberFate := {
  clone := OccMemberFate.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::marker::Copy for pedra_aeneas_group_commit_kernel::OccMemberFate}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:23-87:27 -/
@[reducible]
def OccMemberFate.Insts.CoreMarkerCopy : core.marker.Copy OccMemberFate := {
  cloneInst := OccMemberFate.Insts.CoreCloneClone
}

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::marker::StructuralPartialEq for pedra_aeneas_group_commit_kernel::OccMemberFate}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:29-87:38 -/
@[reducible]
def OccMemberFate.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq OccMemberFate := {
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::cmp::PartialEq<pedra_aeneas_group_commit_kernel::OccMemberFate> for pedra_aeneas_group_commit_kernel::OccMemberFate}::eq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:29-87:38
    Visibility: public -/
def OccMemberFate.Insts.CoreCmpPartialEqOccMemberFate.eq
  (self : OccMemberFate) (other : OccMemberFate) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::cmp::PartialEq<pedra_aeneas_group_commit_kernel::OccMemberFate> for pedra_aeneas_group_commit_kernel::OccMemberFate}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:29-87:38 -/
@[reducible]
def OccMemberFate.Insts.CoreCmpPartialEqOccMemberFate : core.cmp.PartialEq
  OccMemberFate OccMemberFate := {
  eq := OccMemberFate.Insts.CoreCmpPartialEqOccMemberFate.eq
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::cmp::Eq for pedra_aeneas_group_commit_kernel::OccMemberFate}::assert_fields_are_eq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:40-87:42
    Visibility: public -/
def OccMemberFate.Insts.CoreCmpEq.assert_fields_are_eq
  (self : OccMemberFate) : Result Unit := do
  ok ()

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::cmp::Eq for pedra_aeneas_group_commit_kernel::OccMemberFate}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 87:40-87:42 -/
@[reducible]
def OccMemberFate.Insts.CoreCmpEq : core.cmp.Eq OccMemberFate := {
  partialEqInst := OccMemberFate.Insts.CoreCmpPartialEqOccMemberFate
  assert_fields_are_eq := OccMemberFate.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_group_commit_kernel::occ_member_fate]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 99:0-107:1
    Visibility: public -/
def occ_member_fate
  (too_old : Bool) (conflict : Bool) : Result OccMemberFate := do
  if too_old
  then ok OccMemberFate.TooOld
  else if conflict
       then ok OccMemberFate.Conflict
       else ok OccMemberFate.Ok

/-- [pedra_aeneas_group_commit_kernel::occ_member_fate_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 111:0-113:1
    Visibility: public -/
def occ_member_fate_as_is
  (_too_old : Bool) (_conflict : Bool) : Result OccMemberFate := do
  ok OccMemberFate.Ok

/-- [pedra_aeneas_group_commit_kernel::occ_batch_plan]: loop body 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 131:4-139:5
    Visibility: public -/
@[rust_loop_body]
def occ_batch_plan_loop.body
  (too_old : Slice Bool) (reads : Slice OccRead) (last_seq : Std.U64)
  (n : Std.Usize) (out : alloc.vec.Vec OccMemberFate) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec OccMemberFate) × Std.Usize)
    (alloc.vec.Vec OccMemberFate))
  := do
  if i < n
  then
    let or ← Slice.index_usize reads i
    let conflict ← occ_conflict or.snap last_seq or.touched_key_written_after
    let b ← Slice.index_usize too_old i
    let omf ← occ_member_fate b conflict
    let out1 ← alloc.vec.Vec.push out omf
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [pedra_aeneas_group_commit_kernel::occ_batch_plan]: loop 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 131:4-139:5
    Visibility: public -/
@[rust_loop]
def occ_batch_plan_loop
  (too_old : Slice Bool) (reads : Slice OccRead) (last_seq : Std.U64)
  (n : Std.Usize) (out : alloc.vec.Vec OccMemberFate) (i : Std.Usize) :
  Result (alloc.vec.Vec OccMemberFate)
  := do
  loop
    (fun (out1, i1) => occ_batch_plan_loop.body too_old reads last_seq n out1
      i1)
    (out, i)

/-- [pedra_aeneas_group_commit_kernel::occ_batch_plan]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 119:0-141:1
    Visibility: public -/
def occ_batch_plan
  (too_old : Slice Bool) (reads : Slice OccRead) (last_seq : Std.U64) :
  Result (alloc.vec.Vec OccMemberFate)
  := do
  let i := Slice.len too_old
  let i1 := Slice.len reads
  let n ← if i <= i1
            then ok (Slice.len too_old)
            else ok (Slice.len reads)
  let out := alloc.vec.Vec.with_capacity OccMemberFate n
  occ_batch_plan_loop too_old reads last_seq n out 0#usize

/-- [pedra_aeneas_group_commit_kernel::occ_batch_plan_as_is]: loop body 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 157:4-161:5
    Visibility: public -/
@[rust_loop_body]
def occ_batch_plan_as_is_loop.body
  (too_old : Slice Bool) (reads : Slice OccRead) (n : Std.Usize)
  (out : alloc.vec.Vec OccMemberFate) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec OccMemberFate) × Std.Usize)
    (alloc.vec.Vec OccMemberFate))
  := do
  if i < n
  then
    let _ ← Slice.index_usize too_old i
    let _ ← Slice.index_usize reads i
    let out1 ← alloc.vec.Vec.push out OccMemberFate.Ok
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [pedra_aeneas_group_commit_kernel::occ_batch_plan_as_is]: loop 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 157:4-161:5
    Visibility: public -/
@[rust_loop]
def occ_batch_plan_as_is_loop
  (too_old : Slice Bool) (reads : Slice OccRead) (n : Std.Usize)
  (out : alloc.vec.Vec OccMemberFate) (i : Std.Usize) :
  Result (alloc.vec.Vec OccMemberFate)
  := do
  loop
    (fun (out1, i1) => occ_batch_plan_as_is_loop.body too_old reads n out1 i1)
    (out, i)

/-- [pedra_aeneas_group_commit_kernel::occ_batch_plan_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 145:0-163:1
    Visibility: public -/
def occ_batch_plan_as_is
  (too_old : Slice Bool) (reads : Slice OccRead) (_last_seq : Std.U64) :
  Result (alloc.vec.Vec OccMemberFate)
  := do
  let i := Slice.len too_old
  let i1 := Slice.len reads
  let n ← if i <= i1
            then ok (Slice.len too_old)
            else ok (Slice.len reads)
  let out := alloc.vec.Vec.with_capacity OccMemberFate n
  occ_batch_plan_as_is_loop too_old reads n out 0#usize

/-- [pedra_aeneas_group_commit_kernel::fence_publish_seq]: loop body 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 171:4-176:5
    Visibility: public -/
@[rust_loop_body]
def fence_publish_seq_loop.body
  (member_seqs : Slice Std.U64) (best : Std.U64) (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.Usize) Std.U64)
  := do
  let i1 := Slice.len member_seqs
  if i < i1
  then
    let i2 ← Slice.index_usize member_seqs i
    let best1 ← if i2 > best
                  then ok i2
                  else ok best
    let i3 ← i + 1#usize
    ok (cont (best1, i3))
  else ok (done best)

/-- [pedra_aeneas_group_commit_kernel::fence_publish_seq]: loop 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 171:4-176:5
    Visibility: public -/
@[rust_loop]
def fence_publish_seq_loop
  (member_seqs : Slice Std.U64) (best : Std.U64) (i : Std.Usize) :
  Result Std.U64
  := do
  loop
    (fun (best1, i1) => fence_publish_seq_loop.body member_seqs best1 i1)
    (best, i)

/-- [pedra_aeneas_group_commit_kernel::fence_publish_seq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 168:0-178:1
    Visibility: public -/
@[reducible]
def fence_publish_seq (member_seqs : Slice Std.U64) : Result Std.U64 := do
  fence_publish_seq_loop member_seqs 0#u64 0#usize

/-- [pedra_aeneas_group_commit_kernel::fence_publish_seq_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 183:0-189:1
    Visibility: public -/
def fence_publish_seq_as_is
  (member_seqs : Slice Std.U64) : Result Std.U64 := do
  let b ← core.slice.Slice.is_empty member_seqs
  if b
  then ok 0#u64
  else Slice.index_usize member_seqs 0#usize

/-- [pedra_aeneas_group_commit_kernel::occ_conflict_as_is_serialized]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 198:0-205:1
    Visibility: public -/
def occ_conflict_as_is_serialized
  (snap : Std.U64) (last_seq : Std.U64) (writes_before : Std.U64)
  (touched_key_written_after : Bool) :
  Result Bool
  := do
  let i ← last_seq + writes_before
  if i > snap
  then ok touched_key_written_after
  else ok false

/-- [pedra_aeneas_group_commit_kernel::forall_schedules_admitted]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 210:0-212:1
    Visibility: public -/
def forall_schedules_admitted (_pct_depth : Std.U64) : Result Bool := do
  ok false

/-- [pedra_aeneas_group_commit_kernel::forall_schedules_admitted_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 216:0-218:1
    Visibility: public -/
def forall_schedules_admitted_as_is (pct_depth : Std.U64) : Result Bool := do
  ok (pct_depth >= 2#u64)

/-- [pedra_aeneas_group_commit_kernel::pct_campaign_default_depth]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 223:0-225:1
    Visibility: public -/
def pct_campaign_default_depth : Result Std.U64 := do
  ok 2#u64

/-- [pedra_aeneas_group_commit_kernel::default_pct_depth_raised]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 230:0-232:1
    Visibility: public -/
def default_pct_depth_raised : Result Bool := do
  ok false

/-- [pedra_aeneas_group_commit_kernel::default_pct_depth_raised_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 236:0-238:1
    Visibility: public -/
def default_pct_depth_raised_as_is : Result Bool := do
  ok true

/-- [pedra_aeneas_group_commit_kernel::may_publish_group]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 243:0-245:1
    Visibility: public -/
def may_publish_group (wal_io_ok : Bool) : Result Bool := do
  ok wal_io_ok

/-- [pedra_aeneas_group_commit_kernel::rwlock_client_may_mutate]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 252:0-254:1
    Visibility: public -/
def rwlock_client_may_mutate (holding_write : Bool) : Result Bool := do
  ok holding_write

/-- [pedra_aeneas_group_commit_kernel::rwlock_client_may_mutate_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 259:0-261:1
    Visibility: public -/
def rwlock_client_may_mutate_as_is (_holding_write : Bool) : Result Bool := do
  ok true

/-- [pedra_aeneas_group_commit_kernel::may_publish_group_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 265:0-267:1
    Visibility: public -/
def may_publish_group_as_is (_wal_io_ok : Bool) : Result Bool := do
  ok true

/-- [pedra_aeneas_group_commit_kernel::lock_interleavings_admitted]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 272:0-274:1
    Visibility: public -/
def lock_interleavings_admitted : Result Bool := do
  ok false

/-- [pedra_aeneas_group_commit_kernel::lock_interleavings_admitted_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 278:0-280:1
    Visibility: public -/
def lock_interleavings_admitted_as_is : Result Bool := do
  ok true

/-- [pedra_aeneas_group_commit_kernel::fsync_promotes_pending]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 285:0-287:1
    Visibility: public -/
def fsync_promotes_pending (os_honest : Bool) : Result Bool := do
  ok os_honest

/-- [pedra_aeneas_group_commit_kernel::fsync_promotes_pending_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 291:0-293:1
    Visibility: public -/
def fsync_promotes_pending_as_is (_os_honest : Bool) : Result Bool := do
  ok true

/-- [pedra_aeneas_group_commit_kernel::media_durable_admitted]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 297:0-299:1
    Visibility: public -/
def media_durable_admitted (_fsync_ok : Bool) : Result Bool := do
  ok false

/-- [pedra_aeneas_group_commit_kernel::media_durable_admitted_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 303:0-305:1
    Visibility: public -/
def media_durable_admitted_as_is (fsync_ok : Bool) : Result Bool := do
  ok fsync_ok

/-- [pedra_aeneas_group_commit_kernel::stacked_fsync_liars_admitted]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 311:0-313:1
    Visibility: public -/
def stacked_fsync_liars_admitted
  (_lying : Bool) (_det_io : Bool) : Result Bool := do
  ok false

/-- [pedra_aeneas_group_commit_kernel::stacked_fsync_liars_admitted_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 317:0-319:1
    Visibility: public -/
def stacked_fsync_liars_admitted_as_is
  (lying : Bool) (det_io : Bool) : Result Bool := do
  if lying
  then ok det_io
  else ok false

/-- [pedra_aeneas_group_commit_kernel::fsync_lie_closes_tcg_guest]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 324:0-326:1
    Visibility: public -/
def fsync_lie_closes_tcg_guest : Result Bool := do
  ok false

/-- [pedra_aeneas_group_commit_kernel::fsync_lie_closes_tcg_guest_as_is]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 330:0-332:1
    Visibility: public -/
def fsync_lie_closes_tcg_guest_as_is : Result Bool := do
  ok true

end pedra_aeneas_group_commit_kernel
