-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_group_commit_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedra_aeneas_group_commit_kernel

/-- [pedra_aeneas_group_commit_kernel::occ_conflict]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 34:0-36:1
    Visibility: public -/
def occ_conflict
  (snap : Std.U64) (last_seq : Std.U64) (touched_key_written_after : Bool) :
  Result Bool
  := do
  if last_seq > snap
  then ok touched_key_written_after
  else ok false

/-- [pedra_aeneas_group_commit_kernel::OccRead]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 41:0-47:1
    Visibility: public -/
structure OccRead where
  snap : Std.U64
  touched_key_written_after : Bool

/-- [pedra_aeneas_group_commit_kernel::{impl core::fmt::Debug for pedra_aeneas_group_commit_kernel::OccRead}::fmt]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:9-40:14
    Visibility: public -/
def OccRead.Insts.CoreFmtDebug.fmt
  (self : OccRead) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.snap
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool)
      self.touched_key_written_after
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "OccRead") (toStr
    "snap") dyn (toStr "touched_key_written_after") dyn1

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::fmt::Debug for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:9-40:14 -/
@[reducible]
def OccRead.Insts.CoreFmtDebug : core.fmt.Debug OccRead := {
  fmt := OccRead.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::clone::Clone for pedra_aeneas_group_commit_kernel::OccRead}::clone]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:16-40:21
    Visibility: public -/
def OccRead.Insts.CoreCloneClone.clone (self : OccRead) : Result OccRead := do
  ok self

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::clone::Clone for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:16-40:21 -/
@[reducible]
def OccRead.Insts.CoreCloneClone : core.clone.Clone OccRead := {
  clone := OccRead.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::marker::Copy for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:23-40:27 -/
@[reducible]
def OccRead.Insts.CoreMarkerCopy : core.marker.Copy OccRead := {
  cloneInst := OccRead.Insts.CoreCloneClone
}

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::marker::StructuralPartialEq for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:29-40:38 -/
@[reducible]
def OccRead.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq OccRead := {
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::cmp::PartialEq<pedra_aeneas_group_commit_kernel::OccRead> for pedra_aeneas_group_commit_kernel::OccRead}::eq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:29-40:38
    Visibility: public -/
def OccRead.Insts.CoreCmpPartialEqOccRead.eq
  (self : OccRead) (other : OccRead) : Result Bool := do
  if self.snap = other.snap
  then ok (self.touched_key_written_after = other.touched_key_written_after)
  else ok false

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::cmp::PartialEq<pedra_aeneas_group_commit_kernel::OccRead> for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:29-40:38 -/
@[reducible]
def OccRead.Insts.CoreCmpPartialEqOccRead : core.cmp.PartialEq OccRead OccRead
  := {
  eq := OccRead.Insts.CoreCmpPartialEqOccRead.eq
}

/-- [pedra_aeneas_group_commit_kernel::{impl core::cmp::Eq for pedra_aeneas_group_commit_kernel::OccRead}::assert_fields_are_eq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:40-40:42
    Visibility: public -/
def OccRead.Insts.CoreCmpEq.assert_fields_are_eq
  (self : OccRead) : Result Unit := do
  ok ()

/-- Trait implementation: [pedra_aeneas_group_commit_kernel::{impl core::cmp::Eq for pedra_aeneas_group_commit_kernel::OccRead}]
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 40:40-40:42 -/
@[reducible]
def OccRead.Insts.CoreCmpEq : core.cmp.Eq OccRead := {
  partialEqInst := OccRead.Insts.CoreCmpPartialEqOccRead
  assert_fields_are_eq := OccRead.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_group_commit_kernel::group_validate]: loop body 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:4-64:5
    Visibility: public -/
@[rust_loop_body]
def group_validate_loop.body
  (reads : Slice OccRead) (last_seq : Std.U64) (out : alloc.vec.Vec Bool)
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Bool) × Std.Usize) (alloc.vec.Vec Bool))
  := do
  let i1 := Slice.len reads
  if i < i1
  then
    let or ← Slice.index_usize reads i
    let b ← occ_conflict or.snap last_seq or.touched_key_written_after
    let out1 ← alloc.vec.Vec.push out b
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [pedra_aeneas_group_commit_kernel::group_validate]: loop 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 57:4-64:5
    Visibility: public -/
@[rust_loop]
def group_validate_loop
  (reads : Slice OccRead) (last_seq : Std.U64) (out : alloc.vec.Vec Bool)
  (i : Std.Usize) :
  Result (alloc.vec.Vec Bool)
  := do
  loop
    (fun (out1, i1) => group_validate_loop.body reads last_seq out1 i1)
    (out, i)

/-- [pedra_aeneas_group_commit_kernel::group_validate]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 54:0-66:1
    Visibility: public -/
def group_validate
  (reads : Slice OccRead) (last_seq : Std.U64) :
  Result (alloc.vec.Vec Bool)
  := do
  let i := Slice.len reads
  let out := alloc.vec.Vec.with_capacity Bool i
  group_validate_loop reads last_seq out 0#usize

/-- [pedra_aeneas_group_commit_kernel::fence_publish_seq]: loop body 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 74:4-79:5
    Visibility: public -/
@[rust_loop_body]
def fence_publish_seq_loop.body
  (member_seqs : Slice Std.U64) (best : Std.U64) (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.Usize) Std.U64)
  := do
  let i1 := Slice.len member_seqs
  if i < i1
  then
    let i2 ← Slice.index_usize member_seqs i
    let best1 ← if i2 > best
                  then ok i2
                  else ok best
    let i3 ← i + 1#usize
    ok (cont (best1, i3))
  else ok (done best)

/-- [pedra_aeneas_group_commit_kernel::fence_publish_seq]: loop 0:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 74:4-79:5
    Visibility: public -/
@[rust_loop]
def fence_publish_seq_loop
  (member_seqs : Slice Std.U64) (best : Std.U64) (i : Std.Usize) :
  Result Std.U64
  := do
  loop
    (fun (best1, i1) => fence_publish_seq_loop.body member_seqs best1 i1)
    (best, i)

/-- [pedra_aeneas_group_commit_kernel::fence_publish_seq]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 71:0-81:1
    Visibility: public -/
@[reducible]
def fence_publish_seq (member_seqs : Slice Std.U64) : Result Std.U64 := do
  fence_publish_seq_loop member_seqs 0#u64 0#usize

/-- [pedra_aeneas_group_commit_kernel::occ_conflict_as_is_serialized]:
    Source: '../../../crates/pedradb-core/src/group_commit_kernel.rs', lines 90:0-97:1
    Visibility: public -/
def occ_conflict_as_is_serialized
  (snap : Std.U64) (last_seq : Std.U64) (writes_before : Std.U64)
  (touched_key_written_after : Bool) :
  Result Bool
  := do
  let i ← last_seq + writes_before
  if i > snap
  then ok touched_key_written_after
  else ok false

end pedra_aeneas_group_commit_kernel
