-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_group_window_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pedra_aeneas_group_window_kernel

/-- [core::num::error::ParseIntError]
    Source: '/rustc/library/core/src/num/error.rs', lines 74:0-74:24
    Name pattern: [core::num::error::ParseIntError]
    Visibility: public -/
@[rust_type "core::num::error::ParseIntError"]
axiom core.num.error.ParseIntError : Type

/-- Trait declaration: [core::str::traits::FromStr]
    Source: '/rustc/library/core/src/str/traits.rs', lines 883:0-883:30
    Name pattern: [core::str::traits::FromStr]
    Visibility: public -/
@[rust_trait "core::str::traits::FromStr"]
structure core.str.traits.FromStr (Self : Type) (Self_Err : Type) where
  from_str : Str → Result (core.result.Result Self Self_Err)

/-- [core::num::{impl core::str::traits::FromStr<core::num::error::ParseIntError> for u64}::from_str]:
    Source: '/rustc/library/core/src/num/mod.rs', lines 1626:12-1626:68
    Name pattern: [core::num::{core::str::traits::FromStr<u64, core::num::error::ParseIntError>}::from_str]
    Visibility: public -/
@[rust_fun
  "core::num::{core::str::traits::FromStr<u64, core::num::error::ParseIntError>}::from_str"]
axiom U64.Insts.CoreStrTraitsFromStrParseIntError.from_str
  : Str → Result (core.result.Result Std.U64 core.num.error.ParseIntError)

/-- Trait implementation: [core::num::{impl core::str::traits::FromStr<core::num::error::ParseIntError> for u64}]
    Source: '/rustc/library/core/src/num/mod.rs', lines 1589:8-1589:38
    Name pattern: [core::str::traits::FromStr<u64, core::num::error::ParseIntError>] -/
@[reducible, rust_trait_impl
  "core::str::traits::FromStr<u64, core::num::error::ParseIntError>"]
def U64.Insts.CoreStrTraitsFromStrParseIntError : core.str.traits.FromStr
  Std.U64 core.num.error.ParseIntError := {
  from_str := U64.Insts.CoreStrTraitsFromStrParseIntError.from_str
}

/-- [core::result::{core::result::Result<T, E>}::map]:
    Source: '/rustc/library/core/src/result.rs', lines 831:4-833:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map"]
axiom core.result.Result.map
  {T : Type} {E : Type} {U : Type} {F : Type} (opsfunctionFnOnceFTupleTUInst :
  core.ops.function.FnOnce F T U) :
  core.result.Result T E → F → Result (core.result.Result U E)

/-- [core::result::{core::result::Result<T, E>}::unwrap_or]:
    Source: '/rustc/library/core/src/result.rs', lines 1590:4-1593:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::unwrap_or]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::unwrap_or"]
axiom core.result.Result.unwrap_or
  {T : Type} {E : Type} : core.result.Result T E → T → Result T

/-- [core::str::{str}::parse]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 2765:4-2765:56
    Name pattern: [core::str::{str}::parse]
    Visibility: public -/
@[rust_fun "core::str::{str}::parse"]
axiom core.str.Str.parse
  {F : Type} {Clause0_Err : Type} (traitsFromStrInst : core.str.traits.FromStr
  F Clause0_Err) :
  Str → Result (core.result.Result F Clause0_Err)

/-- [core::str::{str}::eq_ignore_ascii_case]:
    Source: '/rustc/library/core/src/str/mod.rs', lines 2840:4-2840:65
    Name pattern: [core::str::{str}::eq_ignore_ascii_case]
    Visibility: public -/
@[rust_fun "core::str::{str}::eq_ignore_ascii_case"]
axiom core.str.Str.eq_ignore_ascii_case : Str → Str → Result Bool

/-- [core::str::traits::{impl core::cmp::PartialEq<str> for str}::eq]:
    Source: '/rustc/library/core/src/str/traits.rs', lines 29:4-29:37
    Name pattern: [core::str::traits::{core::cmp::PartialEq<str, str>}::eq]
    Visibility: public -/
@[rust_fun "core::str::traits::{core::cmp::PartialEq<str, str>}::eq"]
axiom Str.Insts.CoreCmpPartialEqStr.eq : Str → Str → Result Bool

/-- Trait implementation: [core::str::traits::{impl core::cmp::PartialEq<str> for str}]
    Source: '/rustc/library/core/src/str/traits.rs', lines 27:0-27:28
    Name pattern: [core::cmp::PartialEq<str, str>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<str, str>"]
def Str.Insts.CoreCmpPartialEqStr : core.cmp.PartialEq Str Str := {
  eq := Str.Insts.CoreCmpPartialEqStr.eq
}

/-- [pedra_aeneas_group_window_kernel::GROUP_WINDOW_MAX_US]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 27:0-27:43
    Visibility: public -/
@[global_simps, irreducible] def GROUP_WINDOW_MAX_US : Std.U64 := 1000#u64

/-- [pedra_aeneas_group_window_kernel::group_window_us::closure]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 36:17-36:47 -/
@[reducible]
def group_window_us.closure := Unit

/-- [pedra_aeneas_group_window_kernel::group_window_us::{impl core::ops::function::FnOnce<(u64,), u64> for pedra_aeneas_group_window_kernel::group_window_us::closure}::call_once]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 36:17-36:47 -/
def group_window_us.closure.Insts.CoreOpsFunctionFnOnceTupleU64U64.call_once
  (c : group_window_us.closure) (tupled_args : Std.U64) : Result Std.U64 := do
  core.cmp.Ord.min.trait_default core.cmp.OrdU64 tupled_args
    GROUP_WINDOW_MAX_US

/-- Trait implementation: [pedra_aeneas_group_window_kernel::group_window_us::{impl core::ops::function::FnOnce<(u64,), u64> for pedra_aeneas_group_window_kernel::group_window_us::closure}]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 36:17-36:47 -/
@[reducible]
def group_window_us.closure.Insts.CoreOpsFunctionFnOnceTupleU64U64 :
  core.ops.function.FnOnce group_window_us.closure Std.U64 Std.U64 := {
  call_once :=
    group_window_us.closure.Insts.CoreOpsFunctionFnOnceTupleU64U64.call_once
}

/-- [pedra_aeneas_group_window_kernel::group_window_us]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 32:0-40:1
    Visibility: public -/
def group_window_us (raw1 : Option Str) : Result Std.U64 := do
  match raw1 with
  | none => ok 0#u64
  | some s =>
    let r ← core.str.Str.parse U64.Insts.CoreStrTraitsFromStrParseIntError s
    let r1 ←
      core.result.Result.map
        group_window_us.closure.Insts.CoreOpsFunctionFnOnceTupleU64U64 r ()
    core.result.Result.unwrap_or r1 0#u64

/-- [pedra_aeneas_group_window_kernel::merge_eligible]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 50:0-52:1
    Visibility: public -/
def merge_eligible
  (writers : Std.Usize) (window_us : Std.U64) (peers_recent : Bool) :
  Result Bool
  := do
  if window_us > 0#u64
  then if writers >= 2#usize
       then ok true
       else ok peers_recent
  else ok false

/-- [pedra_aeneas_group_window_kernel::async_catchup_bound_us]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 65:0-78:1
    Visibility: public -/
def async_catchup_bound_us
  (window_us : Std.U64) (active : Std.Usize) (batch_len : Std.Usize)
  (peers_recent : Bool) :
  Result Std.U64
  := do
  if window_us = 0#u64
  then ok 0#u64
  else
    if active > batch_len
    then ok window_us
    else if peers_recent
         then ok window_us
         else ok 0#u64

/-- [pedra_aeneas_group_window_kernel::seal_async_first_drain]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 102:0-117:1
    Visibility: public -/
def seal_async_first_drain
  (writers : Std.Usize) (ncpu : Std.Usize) (any_sync : Bool)
  (window_us : Std.U64) (batch_len : Std.Usize) :
  Result Bool
  := do
  if any_sync
  then ok false
  else
    if window_us = 0#u64
    then if writers <= ncpu
         then ok (batch_len = 1#usize)
         else ok false
    else ok false

/-- [pedra_aeneas_group_window_kernel::seal_async_first_drain_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 124:0-132:1
    Visibility: public -/
def seal_async_first_drain_as_is
  (writers : Std.Usize) (ncpu : Std.Usize) (any_sync : Bool)
  (window_us : Std.U64) (_batch_len : Std.Usize) :
  Result Bool
  := do
  if any_sync
  then ok false
  else if window_us = 0#u64
       then ok (writers <= ncpu)
       else ok false

/-- [pedra_aeneas_group_window_kernel::solo_leader_bypass]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 140:0-142:1
    Visibility: public -/
def solo_leader_bypass
  (batch_len : Std.Usize) (queue_len : Std.Usize) (active : Std.Usize) :
  Result Bool
  := do
  if batch_len = 1#usize
  then if queue_len = 0#usize
       then ok (active <= 1#usize)
       else ok false
  else ok false

/-- [pedra_aeneas_group_window_kernel::solo_bypass_armed]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 146:0-148:1
    Visibility: public -/
def solo_bypass_armed (opt_in : Bool) : Result Bool := do
  ok opt_in

/-- [pedra_aeneas_group_window_kernel::solo_leader_bypass_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 153:0-159:1
    Visibility: public -/
def solo_leader_bypass_as_is
  (_batch_len : Std.Usize) (_queue_len : Std.Usize) (_active : Std.Usize) :
  Result Bool
  := do
  ok false

/-- [pedra_aeneas_group_window_kernel::COLLECT_QUIESCE_US]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 164:0-164:39
    Visibility: public -/
@[global_simps, irreducible] def COLLECT_QUIESCE_US : Std.U64 := 20#u64

/-- [pedra_aeneas_group_window_kernel::HERD_COLLECT_US]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 171:0-171:36
    Visibility: public -/
@[global_simps, irreducible] def HERD_COLLECT_US : Std.U64 := 10#u64

/-- [pedra_aeneas_group_window_kernel::HERD_TARGET]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 175:0-175:33
    Visibility: public -/
@[global_simps, irreducible] def HERD_TARGET : Std.Usize := 4#usize

/-- [pedra_aeneas_group_window_kernel::JOIN_LOOK_US]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 181:0-181:33
    Visibility: public -/
@[global_simps, irreducible] def JOIN_LOOK_US : Std.U64 := 20#u64

/-- [pedra_aeneas_group_window_kernel::herd_full]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 197:0-199:1
    Visibility: public -/
def herd_full (batch_len : Std.Usize) : Result Bool := do
  ok (batch_len >= HERD_TARGET)

/-- [pedra_aeneas_group_window_kernel::join_complete]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 185:0-187:1
    Visibility: public -/
def join_complete
  (batch_len : Std.Usize) (active : Std.Usize) : Result Bool := do
  let b ← herd_full batch_len
  if b
  then ok true
  else if active > 0#usize
       then ok (batch_len >= active)
       else ok false

/-- [pedra_aeneas_group_window_kernel::join_complete_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 191:0-193:1
    Visibility: public -/
def join_complete_as_is
  (_batch_len : Std.Usize) (_active : Std.Usize) : Result Bool := do
  ok true

/-- [pedra_aeneas_group_window_kernel::herd_full_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 203:0-205:1
    Visibility: public -/
def herd_full_as_is (_batch_len : Std.Usize) : Result Bool := do
  ok false

/-- [pedra_aeneas_group_window_kernel::herd_collect_us]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 212:0-220:1
    Visibility: public -/
def herd_collect_us
  (active : Std.Usize) (batch_len : Std.Usize) (peers_recent : Bool) :
  Result Std.U64
  := do
  let b ← herd_full batch_len
  if b
  then ok 0#u64
  else
    if active > batch_len
    then ok HERD_COLLECT_US
    else if peers_recent
         then ok HERD_COLLECT_US
         else ok 0#u64

/-- [pedra_aeneas_group_window_kernel::herd_collect_us_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 224:0-226:1
    Visibility: public -/
def herd_collect_us_as_is
  (_active : Std.Usize) (_batch_len : Std.Usize) : Result Std.U64 := do
  ok 0#u64

/-- [pedra_aeneas_group_window_kernel::post_group_grace_us]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 234:0-240:1
    Visibility: public -/
def post_group_grace_us
  (prev_len : Std.Usize) (batch_len : Std.Usize) : Result Std.U64 := do
  if prev_len >= 2#usize
  then let b ← herd_full batch_len
       if b
       then ok 0#u64
       else ok HERD_COLLECT_US
  else ok 0#u64

/-- [pedra_aeneas_group_window_kernel::post_group_grace_us_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 244:0-246:1
    Visibility: public -/
def post_group_grace_us_as_is
  (_prev_len : Std.Usize) (_batch_len : Std.Usize) : Result Std.U64 := do
  ok 0#u64

/-- [pedra_aeneas_group_window_kernel::collect_should_break]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 252:0-254:1
    Visibility: public -/
def collect_should_break
  (quiesce_timed_out : Bool) (batch_len : Std.Usize) (initial_len : Std.Usize)
  :
  Result Bool
  := do
  if quiesce_timed_out
  then ok (batch_len > initial_len)
  else ok false

/-- [pedra_aeneas_group_window_kernel::peer_horizon_us]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 264:0-266:1
    Visibility: public -/
def peer_horizon_us
  (window_us : Std.U64) (base_us : Std.U64) : Result Std.U64 := do
  core.cmp.Ord.max.default core.cmp.OrdU64.partialOrdInst.lt window_us base_us

/-- [pedra_aeneas_group_window_kernel::GROUP_FLIGHT_SEED_US]
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 273:0-273:41
    Visibility: public -/
@[global_simps, irreducible] def GROUP_FLIGHT_SEED_US : Std.U64 := 25#u64

/-- [pedra_aeneas_group_window_kernel::group_window_cap_to_flight]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 278:0-280:1
    Visibility: public -/
def group_window_cap_to_flight (raw1 : Option Str) : Result Bool := do
  match raw1 with
  | none => ok false
  | some s =>
    let b ← Str.Insts.CoreCmpPartialEqStr.eq s (toStr "1")
    if b
    then ok true
    else
      let b1 ← core.str.Str.eq_ignore_ascii_case s (toStr "true")
      if b1
      then ok true
      else ok false

/-- [pedra_aeneas_group_window_kernel::flight_capped_window_us]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 298:0-313:1
    Visibility: public -/
def flight_capped_window_us
  (window_us : Std.U64) (flight_ema_us : Std.U64) (cap_to_flight : Bool) :
  Result Std.U64
  := do
  if cap_to_flight
  then
    if window_us = 0#u64
    then ok window_us
    else
      let flight ←
        if flight_ema_us = 0#u64
        then ok GROUP_FLIGHT_SEED_US
        else ok flight_ema_us
      let capped ←
        core.cmp.Ord.min.trait_default core.cmp.OrdU64 window_us flight
      if capped < COLLECT_QUIESCE_US
      then ok 0#u64
      else ok capped
  else ok window_us

/-- [pedra_aeneas_group_window_kernel::flight_capped_window_us_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 318:0-324:1
    Visibility: public -/
def flight_capped_window_us_as_is
  (window_us : Std.U64) (_flight_ema_us : Std.U64) (_cap_to_flight : Bool) :
  Result Std.U64
  := do
  ok window_us

/-- [pedra_aeneas_group_window_kernel::merge_eligible_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 329:0-331:1
    Visibility: public -/
def merge_eligible_as_is
  (_writers : Std.Usize) (_window_us : Std.U64) : Result Bool := do
  ok false

/-- [pedra_aeneas_group_window_kernel::async_catchup_bound_us_as_is]:
    Source: '../../../crates/pedradb-core/src/group_window_kernel.rs', lines 336:0-342:1
    Visibility: public -/
def async_catchup_bound_us_as_is
  (_window_us : Std.U64) (_active : Std.Usize) (_batch_len : Std.Usize) :
  Result Std.U64
  := do
  ok 0#u64

end pedra_aeneas_group_window_kernel
