-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_key_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pedra_aeneas_key_kernel

/-- [core::cmp::{impl core::cmp::PartialEq<core::cmp::Ordering> for core::cmp::Ordering}::eq]:
    Source: '/rustc/library/core/src/cmp.rs', lines 398:43-398:52
    Name pattern: [core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq]
    Visibility: public -/
@[rust_fun
  "core::cmp::{core::cmp::PartialEq<core::cmp::Ordering, core::cmp::Ordering>}::eq"]
axiom core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq
  : Ordering → Ordering → Result Bool

/-- [core::fmt::num::{impl core::fmt::LowerHex for u8}::fmt]:
    Source: '/rustc/library/core/src/fmt/num.rs', lines 14:12-14:68
    Name pattern: [core::fmt::num::{core::fmt::LowerHex<u8>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::num::{core::fmt::LowerHex<u8>}::fmt"]
axiom U8.Insts.CoreFmtLowerHex.fmt
  :
  Std.U8 → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [core::fmt::num::{impl core::fmt::LowerHex for u8}]
    Source: '/rustc/library/core/src/fmt/num.rs', lines 12:8-12:38
    Name pattern: [core::fmt::LowerHex<u8>] -/
@[reducible, rust_trait_impl "core::fmt::LowerHex<u8>"]
def U8.Insts.CoreFmtLowerHex : core.fmt.LowerHex Std.U8 := {
  fmt := U8.Insts.CoreFmtLowerHex.fmt
}

/-- Trait implementation: [core::fmt::num::imp::{impl core::fmt::Display for usize}]
    Source: '/rustc/library/core/src/fmt/num.rs', lines 134:8-134:39
    Name pattern: [core::fmt::Display<usize>] -/
@[reducible, rust_trait_impl "core::fmt::Display<usize>"]
def Usize.Insts.CoreFmtDisplay : core.fmt.Display Std.Usize := {
  fmt := core.fmt.num.imp.DisplayUsize.fmt
}

/-- [core::hash::impls::{impl core::hash::Hash for u8}::hash]:
    Source: '/rustc/library/core/src/hash/mod.rs', lines 812:16-812:56
    Name pattern: [core::hash::impls::{core::hash::Hash<u8>}::hash]
    Visibility: public -/
@[rust_fun "core::hash::impls::{core::hash::Hash<u8>}::hash"]
axiom U8.Insts.CoreHashHash.hash
  {H : Type} (HasherInst : core.hash.Hasher H) : Std.U8 → H → Result H

/-- [core::hint::must_use]:
    Source: '/rustc/library/core/src/hint.rs', lines 613:0-613:39
    Name pattern: [core::hint::must_use]
    Visibility: public -/
@[rust_fun "core::hint::must_use"]
axiom core.hint.must_use {T : Type} : T → Result T

/-- [core::option::{core::option::Option<T>}::ok_or_else]:
    Source: '/rustc/library/core/src/option.rs', lines 1360:4-1362:52
    Name pattern: [core::option::{core::option::Option<@T>}::ok_or_else]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::ok_or_else"]
axiom core.option.Option.ok_or_else
  {T : Type} {E : Type} {F : Type} (opsfunctionFnOnceFTupleEInst :
  core.ops.function.FnOnce F Unit E) :
  Option T → F → Result (core.result.Result T E)

/-- [core::slice::cmp::{impl core::cmp::Ord for [T]}::cmp]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 39:4-39:42
    Name pattern: [core::slice::cmp::{core::cmp::Ord<[@T]>}::cmp]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::Ord<[@T]>}::cmp"]
axiom Slice.Insts.CoreCmpOrd.cmp
  {T : Type} (cmpOrdInst : core.cmp.Ord T) :
  Slice T → Slice T → Result Ordering

/-- [alloc::fmt::format]:
    Source: '/rustc/library/alloc/src/fmt.rs', lines 649:0-649:52
    Name pattern: [alloc::fmt::format]
    Visibility: public -/
@[rust_fun "alloc::fmt::format"]
axiom alloc.fmt.format : core.fmt.Arguments → Result String

/-- [bytes::bytes::Bytes]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/bytes.rs', lines 101:0-101:16
    Name pattern: [bytes::bytes::Bytes]
    Visibility: public -/
@[rust_type "bytes::bytes::Bytes"]
axiom bytes.bytes.Bytes : Type

/-- [bytes::bytes::{bytes::bytes::Bytes}::len]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/bytes.rs', lines 303:4-303:36
    Name pattern: [bytes::bytes::{bytes::bytes::Bytes}::len]
    Visibility: public -/
@[rust_fun "bytes::bytes::{bytes::bytes::Bytes}::len"]
axiom bytes.bytes.Bytes.len : bytes.bytes.Bytes → Result Std.Usize

/-- [bytes::bytes::{bytes::bytes::Bytes}::copy_from_slice]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/bytes.rs', lines 347:4-347:47
    Name pattern: [bytes::bytes::{bytes::bytes::Bytes}::copy_from_slice]
    Visibility: public -/
@[rust_fun "bytes::bytes::{bytes::bytes::Bytes}::copy_from_slice"]
axiom bytes.bytes.Bytes.copy_from_slice
  : Slice Std.U8 → Result bytes.bytes.Bytes

/-- [bytes::bytes::{impl core::clone::Clone for bytes::bytes::Bytes}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/bytes.rs', lines 676:4-676:28
    Name pattern: [bytes::bytes::{core::clone::Clone<bytes::bytes::Bytes>}::clone]
    Visibility: public -/
@[rust_fun "bytes::bytes::{core::clone::Clone<bytes::bytes::Bytes>}::clone"]
axiom bytes.bytes.Bytes.Insts.CoreCloneClone.clone
  : bytes.bytes.Bytes → Result bytes.bytes.Bytes

/-- [bytes::bytes::{impl core::ops::deref::Deref<[u8]> for bytes::bytes::Bytes}::deref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/bytes.rs', lines 715:4-715:28
    Name pattern: [bytes::bytes::{core::ops::deref::Deref<bytes::bytes::Bytes, [u8]>}::deref]
    Visibility: public -/
@[rust_fun
  "bytes::bytes::{core::ops::deref::Deref<bytes::bytes::Bytes, [u8]>}::deref"]
axiom bytes.bytes.Bytes.Insts.CoreOpsDerefDerefSliceU8.deref
  : bytes.bytes.Bytes → Result (Slice Std.U8)

/-- [bytes::bytes::{impl core::convert::AsRef<[u8]> for bytes::bytes::Bytes}::as_ref]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/bytes.rs', lines 722:4-722:29
    Name pattern: [bytes::bytes::{core::convert::AsRef<bytes::bytes::Bytes, [u8]>}::as_ref]
    Visibility: public -/
@[rust_fun
  "bytes::bytes::{core::convert::AsRef<bytes::bytes::Bytes, [u8]>}::as_ref"]
axiom bytes.bytes.Bytes.Insts.CoreConvertAsRefSliceU8.as_ref
  : bytes.bytes.Bytes → Result (Slice Std.U8)

/-- [bytes::bytes::{impl core::convert::From<alloc::vec::Vec<u8>> for bytes::bytes::Bytes}::from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/bytes.rs', lines 948:4-948:34
    Name pattern: [bytes::bytes::{core::convert::From<bytes::bytes::Bytes, alloc::vec::Vec<u8>>}::from]
    Visibility: public -/
@[rust_fun
  "bytes::bytes::{core::convert::From<bytes::bytes::Bytes, alloc::vec::Vec<u8>>}::from"]
axiom bytes.bytes.Bytes.Insts.CoreConvertFromVecU8.from
  : alloc.vec.Vec Std.U8 → Result bytes.bytes.Bytes

/-- [bytes::fmt::debug::{impl core::fmt::Debug for bytes::bytes::Bytes}::fmt]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/fmt/mod.rs', lines 4:12-4:58
    Name pattern: [bytes::fmt::debug::{core::fmt::Debug<bytes::bytes::Bytes>}::fmt]
    Visibility: public -/
@[rust_fun "bytes::fmt::debug::{core::fmt::Debug<bytes::bytes::Bytes>}::fmt"]
axiom bytes.bytes.Bytes.Insts.CoreFmtDebug.fmt
  :
  bytes.bytes.Bytes → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [bytes::fmt::debug::{impl core::fmt::Debug for bytes::bytes::Bytes}]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bytes-1.12.1/src/fmt/mod.rs', lines 3:8-3:24
    Name pattern: [core::fmt::Debug<bytes::bytes::Bytes>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<bytes::bytes::Bytes>"]
def bytes.bytes.Bytes.Insts.CoreFmtDebug : core.fmt.Debug bytes.bytes.Bytes
  := {
  fmt := bytes.bytes.Bytes.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_key_kernel::key::MAX_SEQUENCE_NUMBER]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 26:0-26:65
    Visibility: public -/
@[global_simps, irreducible]
def key.MAX_SEQUENCE_NUMBER : Result Std.U64 := do
  let i ← 1#u64 <<< 56#i32
  i - 1#u64

/-- [pedra_aeneas_key_kernel::key::ValueType]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 31:0-40:1
    Visibility: public -/
@[discriminant u8]
inductive key.ValueType where
| Deletion : key.ValueType
| Value : key.ValueType
| RangeDeletion : key.ValueType

/-- [pedra_aeneas_key_kernel::key::{impl core::fmt::Debug for pedra_aeneas_key_kernel::key::ValueType}::fmt]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:9-29:14
    Visibility: public -/
def key.ValueType.Insts.CoreFmtDebug.fmt
  (self : key.ValueType) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | key.ValueType.Deletion => core.fmt.Formatter.write_str f (toStr "Deletion")
  | key.ValueType.Value => core.fmt.Formatter.write_str f (toStr "Value")
  | key.ValueType.RangeDeletion =>
    core.fmt.Formatter.write_str f (toStr "RangeDeletion")

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::fmt::Debug for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:9-29:14 -/
@[reducible]
def key.ValueType.Insts.CoreFmtDebug : core.fmt.Debug key.ValueType := {
  fmt := key.ValueType.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_key_kernel::key::{impl core::clone::Clone for pedra_aeneas_key_kernel::key::ValueType}::clone]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:16-29:21
    Visibility: public -/
def key.ValueType.Insts.CoreCloneClone.clone
  (self : key.ValueType) : Result key.ValueType := do
  ok self

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::clone::Clone for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:16-29:21 -/
@[reducible]
def key.ValueType.Insts.CoreCloneClone : core.clone.Clone key.ValueType := {
  clone := key.ValueType.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::marker::Copy for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:23-29:27 -/
@[reducible]
def key.ValueType.Insts.CoreMarkerCopy : core.marker.Copy key.ValueType := {
  cloneInst := key.ValueType.Insts.CoreCloneClone
}

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::marker::StructuralPartialEq for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:29-29:38 -/
@[reducible]
def key.ValueType.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq key.ValueType := {
}

/-- [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialEq<pedra_aeneas_key_kernel::key::ValueType> for pedra_aeneas_key_kernel::key::ValueType}::eq]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:29-29:38
    Visibility: public -/
def key.ValueType.Insts.CoreCmpPartialEqValueType.eq
  (self : key.ValueType) (other : key.ValueType) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialEq<pedra_aeneas_key_kernel::key::ValueType> for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:29-29:38 -/
@[reducible]
def key.ValueType.Insts.CoreCmpPartialEqValueType : core.cmp.PartialEq
  key.ValueType key.ValueType := {
  eq := key.ValueType.Insts.CoreCmpPartialEqValueType.eq
}

/-- [pedra_aeneas_key_kernel::key::{impl core::cmp::Eq for pedra_aeneas_key_kernel::key::ValueType}::assert_fields_are_eq]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:40-29:42
    Visibility: public -/
def key.ValueType.Insts.CoreCmpEq.assert_fields_are_eq
  (self : key.ValueType) : Result Unit := do
  ok ()

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::Eq for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:40-29:42 -/
@[reducible]
def key.ValueType.Insts.CoreCmpEq : core.cmp.Eq key.ValueType := {
  partialEqInst := key.ValueType.Insts.CoreCmpPartialEqValueType
  assert_fields_are_eq := key.ValueType.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_key_kernel::key::{impl core::cmp::Ord for pedra_aeneas_key_kernel::key::ValueType}::cmp]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:56-29:59
    Visibility: public -/
def key.ValueType.Insts.CoreCmpOrd.cmp
  (self : key.ValueType) (other : key.ValueType) : Result Ordering := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (core.cmp.impls.OrdU8.cmp self1 other1)

/-- [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialOrd<pedra_aeneas_key_kernel::key::ValueType> for pedra_aeneas_key_kernel::key::ValueType}::partial_cmp]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:44-29:54
    Visibility: public -/
def key.ValueType.Insts.CoreCmpPartialOrdValueType.partial_cmp
  (self : key.ValueType) (other : key.ValueType) :
  Result (Option Ordering)
  := do
  let o ← key.ValueType.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialOrd<pedra_aeneas_key_kernel::key::ValueType> for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:44-29:54 -/
@[reducible]
def key.ValueType.Insts.CoreCmpPartialOrdValueType : core.cmp.PartialOrd
  key.ValueType key.ValueType := {
  partialEqInst := key.ValueType.Insts.CoreCmpPartialEqValueType
  partial_cmp := key.ValueType.Insts.CoreCmpPartialOrdValueType.partial_cmp
}

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::Ord for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:56-29:59 -/
@[reducible]
def key.ValueType.Insts.CoreCmpOrd : core.cmp.Ord key.ValueType := {
  eqInst := key.ValueType.Insts.CoreCmpEq
  partialOrdInst := key.ValueType.Insts.CoreCmpPartialOrdValueType
  cmp := key.ValueType.Insts.CoreCmpOrd.cmp
}

/-- [pedra_aeneas_key_kernel::key::{impl core::hash::Hash for pedra_aeneas_key_kernel::key::ValueType}::hash]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:61-29:65
    Visibility: public -/
def key.ValueType.Insts.CoreHashHash.hash
  {__H : Type} (corehashHasherInst : core.hash.Hasher __H)
  (self : key.ValueType) (state : __H) :
  Result __H
  := do
  let self1 := read_discriminant self
  U8.Insts.CoreHashHash.hash corehashHasherInst self1 state

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::hash::Hash for pedra_aeneas_key_kernel::key::ValueType}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 29:61-29:65 -/
@[reducible]
def key.ValueType.Insts.CoreHashHash : core.hash.Hash key.ValueType := {
  hash := fun {H : Type} (corehashHasherInst : core.hash.Hasher H) =>
    key.ValueType.Insts.CoreHashHash.hash corehashHasherInst
}

/-- [pedra_aeneas_key_kernel::key::{pedra_aeneas_key_kernel::key::ValueType}::from_u8]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 45:4-52:5
    Visibility: public -/
def key.ValueType.from_u8 (byte : Std.U8) : Result (Option key.ValueType) := do
  match byte with
  | 0#uscalar => ok (some key.ValueType.Deletion)
  | 1#uscalar => ok (some key.ValueType.Value)
  | 2#uscalar => ok (some key.ValueType.RangeDeletion)
  | _ => ok none

/-- [pedra_aeneas_key_kernel::key::{pedra_aeneas_key_kernel::key::ValueType}::as_u8]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 56:4-58:5
    Visibility: public -/
def key.ValueType.as_u8 (self : key.ValueType) : Result Std.U8 := do
  let self1 := read_discriminant self
  ok (UScalar.cast .U8 self1)

/-- [pedra_aeneas_key_kernel::key::pack_sequence_and_type]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 63:0-66:1
    Visibility: public -/
def key.pack_sequence_and_type
  (sequence : Std.U64) (kind : key.ValueType) : Result Std.U64 := do
  let i ← key.MAX_SEQUENCE_NUMBER
  massert (sequence <= i)
  let i1 ← sequence <<< 8#i32
  let i2 ← key.ValueType.as_u8 kind
  let i3 ← lift (core.convert.num.FromU64U8.from i2)
  ok (i1 ||| i3)

/-- [pedra_aeneas_key_kernel::key::pack_sequence_and_type_as_is]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 71:0-73:1
    Visibility: public -/
def key.pack_sequence_and_type_as_is
  (sequence : Std.U64) (kind : key.ValueType) : Result Std.U64 := do
  let i ← key.ValueType.as_u8 kind
  let i1 ← lift (core.convert.num.FromU64U8.from i)
  ok (sequence ||| i1)

/-- [pedra_aeneas_key_kernel::error::CoreError]
    Source: 'src/lib.rs', lines 7:4-10:5
    Visibility: public -/
@[discriminant isize]
inductive error.CoreError where
| Internal : String → error.CoreError

/-- [pedra_aeneas_key_kernel::key::unpack_sequence_and_type::closure]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 81:56-83:5 -/
@[reducible]
def key.unpack_sequence_and_type.closure := Std.U8

/-- [pedra_aeneas_key_kernel::key::unpack_sequence_and_type::{impl core::ops::function::FnOnce<(), pedra_aeneas_key_kernel::error::CoreError> for pedra_aeneas_key_kernel::key::unpack_sequence_and_type::closure<'_0>}::call_once]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 81:56-83:5 -/
def
  key.unpack_sequence_and_type.closure.Insts.CoreOpsFunctionFnOnceTupleCoreError.call_once
  (c : key.unpack_sequence_and_type.closure) (_ : Unit) :
  Result error.CoreError
  := do
  let a ← core.fmt.rt.Argument.new_lower_hex U8.Insts.CoreFmtLowerHex c
  let a1 ←
    core.fmt.Arguments.new
      (Array.make 42#usize [
        33#u8, 117#u8, 110#u8, 107#u8, 110#u8, 111#u8, 119#u8, 110#u8, 32#u8,
        105#u8, 110#u8, 116#u8, 101#u8, 114#u8, 110#u8, 97#u8, 108#u8, 32#u8,
        107#u8, 101#u8, 121#u8, 32#u8, 118#u8, 97#u8, 108#u8, 117#u8, 101#u8,
        32#u8, 116#u8, 121#u8, 112#u8, 101#u8, 58#u8, 32#u8, 195#u8, 32#u8,
        0#u8, 128#u8, 105#u8, 4#u8, 0#u8, 0#u8
        ]) (Array.make 1#usize [ a ])
  let s ← alloc.fmt.format a1
  let s1 ← core.hint.must_use s
  ok (error.CoreError.Internal s1)

/-- Trait implementation: [pedra_aeneas_key_kernel::key::unpack_sequence_and_type::{impl core::ops::function::FnOnce<(), pedra_aeneas_key_kernel::error::CoreError> for pedra_aeneas_key_kernel::key::unpack_sequence_and_type::closure<'_0>}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 81:56-83:5 -/
@[reducible]
def
  key.unpack_sequence_and_type.closure.Insts.CoreOpsFunctionFnOnceTupleCoreError
  : core.ops.function.FnOnce key.unpack_sequence_and_type.closure Unit
  error.CoreError := {
  call_once :=
    key.unpack_sequence_and_type.closure.Insts.CoreOpsFunctionFnOnceTupleCoreError.call_once
}

/-- [pedra_aeneas_key_kernel::key::unpack_sequence_and_type]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 79:0-86:1
    Visibility: public -/
def key.unpack_sequence_and_type
  (packed : Std.U64) :
  Result (core.result.Result (Std.U64 × key.ValueType) error.CoreError)
  := do
  let i ← lift (packed &&& 255#u64)
  let type_byte ← lift (UScalar.cast .U8 i)
  let o ← key.ValueType.from_u8 type_byte
  let r ←
    core.option.Option.ok_or_else
      key.unpack_sequence_and_type.closure.Insts.CoreOpsFunctionFnOnceTupleCoreError
      o type_byte
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let sequence ← packed >>> 8#i32
    ok (core.result.Result.Ok (sequence, val))
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (Std.U64 × key.ValueType) (core.convert.FromSame error.CoreError)
      residual

/-- [pedra_aeneas_key_kernel::key::InternalKey]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 90:0-97:1
    Visibility: public -/
structure key.InternalKey where
  user_key : bytes.bytes.Bytes
  sequence : Std.U64
  kind : key.ValueType

/-- [pedra_aeneas_key_kernel::key::{impl core::fmt::Debug for pedra_aeneas_key_kernel::key::InternalKey}::fmt]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 89:9-89:14
    Visibility: public -/
def key.InternalKey.Insts.CoreFmtDebug.fmt
  (self : key.InternalKey) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ bytes.bytes.Bytes.Insts.CoreFmtDebug self.user_key
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.sequence
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared key.ValueType.Insts.CoreFmtDebug) self.kind
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "InternalKey") (toStr
    "user_key") dyn (toStr "sequence") dyn1 (toStr "kind") dyn2

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::fmt::Debug for pedra_aeneas_key_kernel::key::InternalKey}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 89:9-89:14 -/
@[reducible]
def key.InternalKey.Insts.CoreFmtDebug : core.fmt.Debug key.InternalKey := {
  fmt := key.InternalKey.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_key_kernel::key::{impl core::clone::Clone for pedra_aeneas_key_kernel::key::InternalKey}::clone]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 89:16-89:21
    Visibility: public -/
def key.InternalKey.Insts.CoreCloneClone.clone
  (self : key.InternalKey) : Result key.InternalKey := do
  let b ← bytes.bytes.Bytes.Insts.CoreCloneClone.clone self.user_key
  let i ← lift (core.clone.impls.CloneU64.clone self.sequence)
  let vt ← key.ValueType.Insts.CoreCloneClone.clone self.kind
  ok { user_key := b, sequence := i, kind := vt }

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::clone::Clone for pedra_aeneas_key_kernel::key::InternalKey}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 89:16-89:21 -/
@[reducible]
def key.InternalKey.Insts.CoreCloneClone : core.clone.Clone key.InternalKey
  := {
  clone := key.InternalKey.Insts.CoreCloneClone.clone
}

/-- [pedra_aeneas_key_kernel::key::{pedra_aeneas_key_kernel::key::InternalKey}::new]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 102:4-108:5
    Visibility: public -/
def key.InternalKey.new
  {T0 : Type} (coreconvertIntoT0BytesInst : core.convert.Into T0
  bytes.bytes.Bytes) (user_key : T0) (sequence : Std.U64)
  (kind : key.ValueType) :
  Result key.InternalKey
  := do
  let b ← coreconvertIntoT0BytesInst.into user_key
  ok { user_key := b, sequence, kind }

/-- [pedra_aeneas_key_kernel::key::{pedra_aeneas_key_kernel::key::InternalKey}::for_lookup]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 112:4-114:5
    Visibility: public -/
def key.InternalKey.for_lookup
  {T0 : Type} (coreconvertIntoT0BytesInst : core.convert.Into T0
  bytes.bytes.Bytes) (user_key : T0) (snapshot : Std.U64) :
  Result key.InternalKey
  := do
  key.InternalKey.new coreconvertIntoT0BytesInst user_key snapshot
    key.ValueType.Value

/-- [pedra_aeneas_key_kernel::key::{pedra_aeneas_key_kernel::key::InternalKey}::encode_into]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 125:4-129:5
    Visibility: public -/
def key.InternalKey.encode_into
  (self : key.InternalKey) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let s ←
    bytes.bytes.Bytes.Insts.CoreOpsDerefDerefSliceU8.deref self.user_key
  let out1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out s
  let packed ← key.pack_sequence_and_type self.sequence self.kind
  let a ← lift (core.num.U64.to_be_bytes packed)
  let s1 ← lift (Array.to_slice a)
  alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out1 s1

/-- [pedra_aeneas_key_kernel::key::{pedra_aeneas_key_kernel::key::InternalKey}::encode]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 118:4-122:5
    Visibility: public -/
def key.InternalKey.encode
  (self : key.InternalKey) : Result bytes.bytes.Bytes := do
  let i ← bytes.bytes.Bytes.len self.user_key
  let i1 ← i + 8#usize
  let buf := alloc.vec.Vec.with_capacity Std.U8 i1
  let buf1 ← key.InternalKey.encode_into self buf
  bytes.bytes.Bytes.Insts.CoreConvertFromVecU8.from buf1

/-- [pedra_aeneas_key_kernel::key::{pedra_aeneas_key_kernel::key::InternalKey}::decode]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 136:4-154:5
    Visibility: public -/
def key.InternalKey.decode
  (encoded : Slice Std.U8) :
  Result (core.result.Result key.InternalKey error.CoreError)
  := do
  let i := Slice.len encoded
  if i < 8#usize
  then
    let args := Slice.len encoded
    let a ← core.fmt.rt.Argument.new_display Usize.Insts.CoreFmtDisplay args
    let a1 ←
      core.fmt.Arguments.new
        (Array.make 34#usize [
          24#u8, 105#u8, 110#u8, 116#u8, 101#u8, 114#u8, 110#u8, 97#u8, 108#u8,
          32#u8, 107#u8, 101#u8, 121#u8, 32#u8, 116#u8, 111#u8, 111#u8, 32#u8,
          115#u8, 104#u8, 111#u8, 114#u8, 116#u8, 58#u8, 32#u8, 192#u8, 6#u8,
          32#u8, 98#u8, 121#u8, 116#u8, 101#u8, 115#u8, 0#u8
          ]) (Array.make 1#usize [ a ])
    let s ← alloc.fmt.format a1
    let s1 ← core.hint.must_use s
    ok (core.result.Result.Err (error.CoreError.Internal s1))
  else
    let i1 := Slice.len encoded
    let split ← i1 - 8#usize
    let s ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8) encoded
        { «end» := split }
    let user_key ← bytes.bytes.Bytes.copy_from_slice s
    let trailer := Array.repeat 8#usize 0#u8
    let (s1, to_slice_mut_back) ← lift (Array.to_slice_mut trailer)
    let s2 ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) encoded
        { start := split }
    let s3 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s1 s2
    let trailer1 := to_slice_mut_back s3
    let packed ← lift (core.num.U64.from_be_bytes trailer1)
    let r ← key.unpack_sequence_and_type packed
    let cf ← core.result.Result.Insts.CoreOpsTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      let (sequence, kind) := val
      ok (core.result.Result.Ok { user_key, sequence, kind })
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        key.InternalKey (core.convert.FromSame error.CoreError) residual

/-- [pedra_aeneas_key_kernel::key::ikey_seq_cmp]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 188:0-190:1
    Visibility: public -/
def key.ikey_seq_cmp (a : Std.U64) (b : Std.U64) : Result Ordering := do
  ok (core.cmp.impls.OrdU64.cmp b a)

/-- [pedra_aeneas_key_kernel::key::{impl core::cmp::Ord for pedra_aeneas_key_kernel::key::InternalKey}::cmp]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 172:4-183:5
    Visibility: public -/
def key.InternalKey.Insts.CoreCmpOrd.cmp
  (self : key.InternalKey) (other : key.InternalKey) : Result Ordering := do
  let s ←
    bytes.bytes.Bytes.Insts.CoreConvertAsRefSliceU8.as_ref self.user_key
  let s1 ←
    bytes.bytes.Bytes.Insts.CoreConvertAsRefSliceU8.as_ref other.user_key
  let o ← Slice.Insts.CoreCmpOrd.cmp core.cmp.OrdU8 s s1
  match o with
  | Ordering.lt => ok Ordering.lt
  | Ordering.eq =>
    let o1 ← key.ikey_seq_cmp self.sequence other.sequence
    match o1 with
    | Ordering.lt => ok Ordering.lt
    | Ordering.eq => key.ValueType.Insts.CoreCmpOrd.cmp other.kind self.kind
    | Ordering.gt => ok Ordering.gt
  | Ordering.gt => ok Ordering.gt

/-- [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialEq<pedra_aeneas_key_kernel::key::InternalKey> for pedra_aeneas_key_kernel::key::InternalKey}::eq]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 158:4-160:5
    Visibility: public -/
def key.InternalKey.Insts.CoreCmpPartialEqInternalKey.eq
  (self : key.InternalKey) (other : key.InternalKey) : Result Bool := do
  let o ← key.InternalKey.Insts.CoreCmpOrd.cmp self other
  core.cmp.Ordering.Insts.CoreCmpPartialEqOrdering.eq o Ordering.eq

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialEq<pedra_aeneas_key_kernel::key::InternalKey> for pedra_aeneas_key_kernel::key::InternalKey}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 157:0-161:1 -/
@[reducible]
def key.InternalKey.Insts.CoreCmpPartialEqInternalKey : core.cmp.PartialEq
  key.InternalKey key.InternalKey := {
  eq := key.InternalKey.Insts.CoreCmpPartialEqInternalKey.eq
}

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::Eq for pedra_aeneas_key_kernel::key::InternalKey}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 163:0-163:26 -/
def key.InternalKey.Insts.CoreCmpEq.assert_fields_are_eq
  (self : key.InternalKey) : Result Unit := do
  ok ()

@[reducible]
def key.InternalKey.Insts.CoreCmpEq : core.cmp.Eq key.InternalKey := {
  partialEqInst := key.InternalKey.Insts.CoreCmpPartialEqInternalKey
  assert_fields_are_eq := key.InternalKey.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialOrd<pedra_aeneas_key_kernel::key::InternalKey> for pedra_aeneas_key_kernel::key::InternalKey}::partial_cmp]:
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 166:4-168:5
    Visibility: public -/
def key.InternalKey.Insts.CoreCmpPartialOrdInternalKey.partial_cmp
  (self : key.InternalKey) (other : key.InternalKey) :
  Result (Option Ordering)
  := do
  let o ← key.InternalKey.Insts.CoreCmpOrd.cmp self other
  ok (some o)

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::PartialOrd<pedra_aeneas_key_kernel::key::InternalKey> for pedra_aeneas_key_kernel::key::InternalKey}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 165:0-169:1 -/
@[reducible]
def key.InternalKey.Insts.CoreCmpPartialOrdInternalKey : core.cmp.PartialOrd
  key.InternalKey key.InternalKey := {
  partialEqInst := key.InternalKey.Insts.CoreCmpPartialEqInternalKey
  partial_cmp := key.InternalKey.Insts.CoreCmpPartialOrdInternalKey.partial_cmp
}

/-- Trait implementation: [pedra_aeneas_key_kernel::key::{impl core::cmp::Ord for pedra_aeneas_key_kernel::key::InternalKey}]
    Source: 'src/../../../../crates/pedradb-core/src/key_kernel.rs', lines 171:0-184:1 -/
@[reducible]
def key.InternalKey.Insts.CoreCmpOrd : core.cmp.Ord key.InternalKey := {
  eqInst := key.InternalKey.Insts.CoreCmpEq
  partialOrdInst := key.InternalKey.Insts.CoreCmpPartialOrdInternalKey
  cmp := key.InternalKey.Insts.CoreCmpOrd.cmp
}

end pedra_aeneas_key_kernel
