-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_leftover_page_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pedra_aeneas_leftover_page_kernel

/-- [core::cmp::impls::{impl core::cmp::PartialOrd<&'_0 B> for &'_1 A}::lt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2141:8-2141:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- [core::cmp::impls::{impl core::cmp::PartialOrd<&'_0 B> for &'_1 A}::ge]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2153:8-2153:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::ge]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::ge"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.ge
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialEq<[U]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 14:0-16:28
    Name pattern: [core::cmp::PartialEq<[@T], [@U]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T], [@U]>"]
def Slice.Insts.CoreCmpPartialEqSlice {T : Type} {U : Type} (cmpPartialEqInst :
  core.cmp.PartialEq T U) : core.cmp.PartialEq (Slice T) (Slice U) := {
  eq := core.slice.cmp.PartialEqSlice.eq cmpPartialEqInst
}

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::ge]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 84:4-84:38
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::ge]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::ge"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.ge
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result Bool

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::lt]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 64:4-64:38
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::lt]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::lt"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.lt
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result Bool

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::partial_cmp]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 60:4-60:58
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::partial_cmp"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.partial_cmp
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result (Option Ordering)

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 58:0-58:52
    Name pattern: [core::cmp::PartialOrd<[@T], [@T]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialOrd<[@T], [@T]>"]
def Slice.Insts.CoreCmpPartialOrdSlice {T : Type} (cmpPartialOrdInst :
  core.cmp.PartialOrd T T) : core.cmp.PartialOrd (Slice T) (Slice T) := {
  partialEqInst := Slice.Insts.CoreCmpPartialEqSlice
    cmpPartialOrdInst.partialEqInst
  partial_cmp := Slice.Insts.CoreCmpPartialOrdSlice.partial_cmp
    cmpPartialOrdInst
  lt := Slice.Insts.CoreCmpPartialOrdSlice.lt cmpPartialOrdInst
  ge := Slice.Insts.CoreCmpPartialOrdSlice.ge cmpPartialOrdInst
}

/-- [alloc::vec::{alloc::vec::Vec<T>}::truncate]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1814:4-1814:42
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::truncate]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::truncate"]
axiom alloc.vec.Vec.truncate
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (alloc.vec.Vec T)

/-- [alloc::vec::{alloc::vec::Vec<T>}::as_slice]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1854:4-1854:40
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::as_slice]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::as_slice"]
axiom alloc.vec.Vec.as_slice
  {T : Type} (A : Type) : alloc.vec.Vec T → Result (Slice T)

/-- [pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice]
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 17:0-28:1
    Visibility: public -/
@[discriminant isize]
inductive LeftoverPageAdvice where
| Drop : LeftoverPageAdvice
| KeepHot : LeftoverPageAdvice
| KeepCovered : LeftoverPageAdvice
| KeepDefault : LeftoverPageAdvice

/-- [pedra_aeneas_leftover_page_kernel::{impl core::fmt::Debug for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}::fmt]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:9-16:14
    Visibility: public -/
def LeftoverPageAdvice.Insts.CoreFmtDebug.fmt
  (self : LeftoverPageAdvice) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | LeftoverPageAdvice.Drop => core.fmt.Formatter.write_str f (toStr "Drop")
  | LeftoverPageAdvice.KeepHot =>
    core.fmt.Formatter.write_str f (toStr "KeepHot")
  | LeftoverPageAdvice.KeepCovered =>
    core.fmt.Formatter.write_str f (toStr "KeepCovered")
  | LeftoverPageAdvice.KeepDefault =>
    core.fmt.Formatter.write_str f (toStr "KeepDefault")

/-- Trait implementation: [pedra_aeneas_leftover_page_kernel::{impl core::fmt::Debug for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}]
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:9-16:14 -/
@[reducible]
def LeftoverPageAdvice.Insts.CoreFmtDebug : core.fmt.Debug LeftoverPageAdvice
  := {
  fmt := LeftoverPageAdvice.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_leftover_page_kernel::{impl core::clone::Clone for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}::clone]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:16-16:21
    Visibility: public -/
def LeftoverPageAdvice.Insts.CoreCloneClone.clone
  (self : LeftoverPageAdvice) : Result LeftoverPageAdvice := do
  ok self

/-- Trait implementation: [pedra_aeneas_leftover_page_kernel::{impl core::clone::Clone for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}]
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:16-16:21 -/
@[reducible]
def LeftoverPageAdvice.Insts.CoreCloneClone : core.clone.Clone
  LeftoverPageAdvice := {
  clone := LeftoverPageAdvice.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pedra_aeneas_leftover_page_kernel::{impl core::marker::Copy for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}]
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:23-16:27 -/
@[reducible]
def LeftoverPageAdvice.Insts.CoreMarkerCopy : core.marker.Copy
  LeftoverPageAdvice := {
  cloneInst := LeftoverPageAdvice.Insts.CoreCloneClone
}

/-- Trait implementation: [pedra_aeneas_leftover_page_kernel::{impl core::marker::StructuralPartialEq for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}]
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:29-16:38 -/
@[reducible]
def LeftoverPageAdvice.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq LeftoverPageAdvice := {
}

/-- [pedra_aeneas_leftover_page_kernel::{impl core::cmp::PartialEq<pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice> for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}::eq]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:29-16:38
    Visibility: public -/
def LeftoverPageAdvice.Insts.CoreCmpPartialEqLeftoverPageAdvice.eq
  (self : LeftoverPageAdvice) (other : LeftoverPageAdvice) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [pedra_aeneas_leftover_page_kernel::{impl core::cmp::PartialEq<pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice> for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}]
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:29-16:38 -/
@[reducible]
def LeftoverPageAdvice.Insts.CoreCmpPartialEqLeftoverPageAdvice :
  core.cmp.PartialEq LeftoverPageAdvice LeftoverPageAdvice := {
  eq := LeftoverPageAdvice.Insts.CoreCmpPartialEqLeftoverPageAdvice.eq
}

/-- [pedra_aeneas_leftover_page_kernel::{impl core::cmp::Eq for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}::assert_fields_are_eq]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:40-16:42
    Visibility: public -/
def LeftoverPageAdvice.Insts.CoreCmpEq.assert_fields_are_eq
  (self : LeftoverPageAdvice) : Result Unit := do
  ok ()

/-- Trait implementation: [pedra_aeneas_leftover_page_kernel::{impl core::cmp::Eq for pedra_aeneas_leftover_page_kernel::LeftoverPageAdvice}]
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 16:40-16:42 -/
@[reducible]
def LeftoverPageAdvice.Insts.CoreCmpEq : core.cmp.Eq LeftoverPageAdvice := {
  partialEqInst := LeftoverPageAdvice.Insts.CoreCmpPartialEqLeftoverPageAdvice
  assert_fields_are_eq :=
    LeftoverPageAdvice.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_leftover_page_kernel::leftover_page_advice]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 35:0-51:1
    Visibility: public -/
def leftover_page_advice
  (sst_page_keep_budget : Std.U64) (sst_bytes : Std.U64)
  (warm_cap_bytes : Std.U64) (live_family_covered_by_sst : Bool) :
  Result LeftoverPageAdvice
  := do
  if sst_page_keep_budget != 0#u64
  then ok LeftoverPageAdvice.KeepDefault
  else
    if live_family_covered_by_sst
    then ok LeftoverPageAdvice.KeepCovered
    else
      if sst_bytes <= warm_cap_bytes
      then ok LeftoverPageAdvice.KeepHot
      else ok LeftoverPageAdvice.Drop

/-- [pedra_aeneas_leftover_page_kernel::leftover_page_advice_as_is]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 55:0-62:1
    Visibility: public -/
def leftover_page_advice_as_is
  (_sst_page_keep_budget : Std.U64) (_sst_bytes : Std.U64)
  (_warm_cap_bytes : Std.U64) (_live_family_covered_by_sst : Bool) :
  Result LeftoverPageAdvice
  := do
  ok LeftoverPageAdvice.KeepDefault

/-- [pedra_aeneas_leftover_page_kernel::family_upper_bound]: loop body 0:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 74:4-85:1
    Visibility: public -/
@[rust_loop_body]
def family_upper_bound_loop.body
  (pfx : Slice Std.U8) (i : Std.Usize) :
  Result (ControlFlow Std.Usize (Option (alloc.vec.Vec Std.U8)))
  := do
  if i > 0#usize
  then
    let i1 ← i - 1#usize
    let b ← Slice.index_usize pfx i1
    if b < 255#u8
    then
      let hi ← alloc.slice.Slice.to_vec core.clone.CloneU8 pfx
      let i2 ← lift (core.num.U8.wrapping_add b 1#u8)
      let (_, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U8)
          hi i1
      let hi1 := index_mut_back i2
      let i3 ← i1 + 1#usize
      let hi2 ← alloc.vec.Vec.truncate Global hi1 i3
      ok (done (some hi2))
    else ok (cont i1)
  else ok (done none)

/-- [pedra_aeneas_leftover_page_kernel::family_upper_bound]: loop 0:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 74:4-85:1
    Visibility: public -/
@[rust_loop]
def family_upper_bound_loop
  (pfx : Slice Std.U8) (i : Std.Usize) :
  Result (Option (alloc.vec.Vec Std.U8))
  := do
  loop
    (fun i1 => family_upper_bound_loop.body pfx i1)
    i

/-- [pedra_aeneas_leftover_page_kernel::family_upper_bound]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 69:0-85:1
    Visibility: public -/
def family_upper_bound
  (pfx : Slice Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  let i := Slice.len pfx
  family_upper_bound_loop pfx i

/-- [pedra_aeneas_leftover_page_kernel::sst_range_covers_family]:
    Source: '../../../crates/pedradb-core/src/leftover_page_kernel.rs', lines 93:0-106:1
    Visibility: public -/
def sst_range_covers_family
  (smallest : Option (Slice Std.U8)) (largest : Option (Slice Std.U8))
  (pfx : Slice Std.U8) :
  Result Bool
  := do
  match smallest with
  | none => ok false
  | some lo =>
    match largest with
    | none => ok false
    | some hi =>
      let o ← family_upper_bound pfx
      match o with
      | none =>
        Shared1A.Insts.CoreCmpPartialOrdShared0B.ge
          (Slice.Insts.CoreCmpPartialOrdSlice core.cmp.PartialOrdU8) hi pfx
      | some fam_hi_excl =>
        let b ←
          Shared1A.Insts.CoreCmpPartialOrdShared0B.ge
            (Slice.Insts.CoreCmpPartialOrdSlice core.cmp.PartialOrdU8) hi pfx
        if b
        then
          let s ← alloc.vec.Vec.as_slice Global fam_hi_excl
          Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
            (Slice.Insts.CoreCmpPartialOrdSlice core.cmp.PartialOrdU8) lo s
        else ok false

end pedra_aeneas_leftover_page_kernel
