-- AUTO-GENERATED by scripts/ratchet/derive_count_annotations.py
-- RFC-0204 P0.1 — retired mirror: the Nat count-twin layer of the
-- lsm_compact walk is MACHINE-EMITTED from the declared twin shape,
-- validated against the same parse that derives step_work (drain fn
-- makes exactly 1 nested enrolled call; emitted theorem name equals the
-- registered count row). DO NOT EDIT: regenerate with
--   python3 scripts/ratchet/derive_count_annotations.py
-- (scripts/lean_extracts.sh gates on --check before building). The
-- semantic bridges to the real extract stay HUMAN, by design, in
-- LsmCompactBridges.lean.
import Aeneas
import LsmR1Kernel
open Aeneas Aeneas.Std Result ControlFlow
open pedra_aeneas_lsm_r1_kernel

/-! ## Count twins (pure Nat, machine-emitted) -/

/-- Work twin of the compact inner loop: iterations while `remaining`
entries are left to consume (`remaining` is the loop's own decreasing
measure `src_len - i`) — one step per consumed entry. -/
def lsm_compact_steps : Nat → Nat
  | 0 => 0
  | remaining + 1 => 1 + lsm_compact_steps remaining

/-- Logical length (`len`) of level `lvl` of `s`; 0 when out of range. -/
def lsm_level_len (s : LsmState) (lvl : Nat) : Nat :=
  match s.levels.val[lvl]? with
  | some l => l.len.val
  | none => 0

/-- Entries stored strictly below `depth` — the compact drain set. -/
def lsm_entries_below (s : LsmState) : Nat → Nat
  | 0 => 0
  | lvl + 1 => lsm_level_len s lvl + lsm_entries_below s lvl

/-- Work twin of the whole compact walk: one inner pass over each source
level's stored entries plus one bookkeeping iteration per drained level. -/
def lsm_compact_src_steps (s : LsmState) : Nat → Nat
  | 0 => 0
  | lvl + 1 => lsm_compact_steps (lsm_level_len s lvl) + 1 + lsm_compact_src_steps s lvl

/-- Inner twin bound: one iteration per remaining entry, no more. -/
theorem lsm_compact_steps_le : ∀ (remaining : Nat),
    lsm_compact_steps remaining ≤ remaining := by
  intro remaining
  induction remaining with
  | zero => simp [lsm_compact_steps]
  | succ d ih => simp only [lsm_compact_steps]; omega

/-- RFC-0199 count (P0.2), machine-emitted since RFC-0204 P0.1: the
compact walk's work twin never exceeds the entries stored below the
target level plus one bookkeeping iteration per drained level — one-pass
over the stored data, independent of how often compact is called or how
big the deeper (untouched) levels are. -/
theorem lsm_compact_work_bound : ∀ (s : LsmState) (depth : Nat),
    lsm_compact_src_steps s depth ≤ lsm_entries_below s depth + depth := by
  intro s depth
  induction depth with
  | zero => simp [lsm_compact_src_steps, lsm_entries_below]
  | succ lvl ih =>
    have h := lsm_compact_steps_le (lsm_level_len s lvl)
    simp only [lsm_compact_src_steps, lsm_entries_below]
    omega
