-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_posix_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedra_aeneas_posix_kernel

/-- [pedra_aeneas_posix_kernel::fdatasync_rc_ok]:
    Source: '../../../crates/pedradb-posix/src/lib.rs', lines 37:0-39:1
    Visibility: public -/
def fdatasync_rc_ok (rc : Std.I32) : Result Bool := do
  ok (rc = 0#i32)

/-- [pedra_aeneas_posix_kernel::fdatasync_rc_ok_as_is]:
    Source: '../../../crates/pedradb-posix/src/lib.rs', lines 43:0-45:1
    Visibility: public -/
def fdatasync_rc_ok_as_is (_rc : Std.I32) : Result Bool := do
  ok true

/-- [pedra_aeneas_posix_kernel::fdatasync_eintr_retry_admitted]:
    Source: '../../../crates/pedradb-posix/src/lib.rs', lines 51:0-53:1
    Visibility: public -/
def fdatasync_eintr_retry_admitted : Result Bool := do
  ok false

/-- [pedra_aeneas_posix_kernel::fdatasync_eintr_retry_admitted_as_is]:
    Source: '../../../crates/pedradb-posix/src/lib.rs', lines 57:0-59:1
    Visibility: public -/
def fdatasync_eintr_retry_admitted_as_is : Result Bool := do
  ok true

end pedra_aeneas_posix_kernel
