-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_prefix_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pedra_aeneas_prefix_kernel

/-- [core::cmp::impls::{impl core::cmp::PartialOrd<&'_0 B> for &'_1 A}::lt]:
    Source: '/rustc/library/core/src/cmp.rs', lines 2141:8-2141:40
    Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt]
    Visibility: public -/
@[rust_fun "core::cmp::impls::{core::cmp::PartialOrd<&'1 @A, &'0 @B>}::lt"]
axiom Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
  {A : Type} {B : Type} (PartialOrdInst : core.cmp.PartialOrd A B) :
  A → B → Result Bool

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialEq<[U]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 14:0-16:28
    Name pattern: [core::cmp::PartialEq<[@T], [@U]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T], [@U]>"]
def Slice.Insts.CoreCmpPartialEqSlice {T : Type} {U : Type} (cmpPartialEqInst :
  core.cmp.PartialEq T U) : core.cmp.PartialEq (Slice T) (Slice U) := {
  eq := core.slice.cmp.PartialEqSlice.eq cmpPartialEqInst
}

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::lt]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 64:4-64:38
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::lt]
    Visibility: public -/
@[rust_fun "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::lt"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.lt
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result Bool

/-- [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}::partial_cmp]:
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 60:4-60:58
    Name pattern: [core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::partial_cmp]
    Visibility: public -/
@[rust_fun
  "core::slice::cmp::{core::cmp::PartialOrd<[@T], [@T]>}::partial_cmp"]
axiom Slice.Insts.CoreCmpPartialOrdSlice.partial_cmp
  {T : Type} (cmpPartialOrdInst : core.cmp.PartialOrd T T) :
  Slice T → Slice T → Result (Option Ordering)

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialOrd<[T]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 58:0-58:52
    Name pattern: [core::cmp::PartialOrd<[@T], [@T]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialOrd<[@T], [@T]>"]
def Slice.Insts.CoreCmpPartialOrdSlice {T : Type} (cmpPartialOrdInst :
  core.cmp.PartialOrd T T) : core.cmp.PartialOrd (Slice T) (Slice T) := {
  partialEqInst := Slice.Insts.CoreCmpPartialEqSlice
    cmpPartialOrdInst.partialEqInst
  partial_cmp := Slice.Insts.CoreCmpPartialOrdSlice.partial_cmp
    cmpPartialOrdInst
  lt := Slice.Insts.CoreCmpPartialOrdSlice.lt cmpPartialOrdInst
}

/-- [core::slice::{[T]}::starts_with]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 2620:4-2622:21
    Name pattern: [core::slice::{[@T]}::starts_with]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::starts_with"]
axiom core.slice.Slice.starts_with
  {T : Type} (cmpPartialEqInst : core.cmp.PartialEq T T) :
  Slice T → Slice T → Result Bool

/-- [alloc::vec::{alloc::vec::Vec<T>}::pop]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 2850:4-2850:38
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::pop]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::pop"]
axiom alloc.vec.Vec.pop
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Result ((Option T) × (alloc.vec.Vec T))

/-- [pedra_aeneas_prefix_kernel::prefix_exclusive_end]: loop body 0:
    Source: '../../../crates/pedradb-core/src/prefix_kernel.rs', lines 18:4-27:1
    Visibility: public -/
@[rust_loop_body]
def prefix_exclusive_end_loop.body
  (e : alloc.vec.Vec Std.U8) :
  Result (ControlFlow (alloc.vec.Vec Std.U8) (Option (alloc.vec.Vec Std.U8)))
  := do
  let i := alloc.vec.Vec.len e
  if i > 0#usize
  then
    let i1 := alloc.vec.Vec.len e
    let i2 ← i1 - 1#usize
    let i3 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8) e i2
    if i3 < 255#u8
    then
      let (i4, index_mut_back) ←
        alloc.vec.Vec.index_mut (core.slice.index.SliceIndexUsizeSlice Std.U8)
          e i2
      let i5 ← i4 + 1#u8
      let e1 := index_mut_back i5
      ok (done (some e1))
    else let (_, e1) ← alloc.vec.Vec.pop Global e
         ok (cont e1)
  else ok (done none)

/-- [pedra_aeneas_prefix_kernel::prefix_exclusive_end]: loop 0:
    Source: '../../../crates/pedradb-core/src/prefix_kernel.rs', lines 18:4-27:1
    Visibility: public -/
@[rust_loop]
def prefix_exclusive_end_loop
  (e : alloc.vec.Vec Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  loop
    (fun e1 => prefix_exclusive_end_loop.body e1)
    e

/-- [pedra_aeneas_prefix_kernel::prefix_exclusive_end]:
    Source: '../../../crates/pedradb-core/src/prefix_kernel.rs', lines 16:0-27:1
    Visibility: public -/
def prefix_exclusive_end
  (prefix1 : Slice Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  let e ← alloc.slice.Slice.to_vec core.clone.CloneU8 prefix1
  prefix_exclusive_end_loop e

/-- [pedra_aeneas_prefix_kernel::prefix_exclusive_end_as_is]:
    Source: '../../../crates/pedradb-core/src/prefix_kernel.rs', lines 31:0-35:1
    Visibility: public -/
def prefix_exclusive_end_as_is
  (prefix1 : Slice Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  let e ← alloc.slice.Slice.to_vec core.clone.CloneU8 prefix1
  let e1 ← alloc.vec.Vec.push e 255#u8
  ok (some e1)

/-- [pedra_aeneas_prefix_kernel::key_in_prefix_range]:
    Source: '../../../crates/pedradb-core/src/prefix_kernel.rs', lines 39:0-47:1
    Visibility: public -/
def key_in_prefix_range
  (key : Slice Std.U8) (prefix1 : Slice Std.U8) (end1 : Option (Slice Std.U8))
  :
  Result Bool
  := do
  let b ← core.slice.Slice.starts_with core.cmp.PartialEqU8 key prefix1
  if b
  then
    match end1 with
    | none => ok true
    | some e =>
      Shared1A.Insts.CoreCmpPartialOrdShared0B.lt
        (Slice.Insts.CoreCmpPartialOrdSlice core.cmp.PartialOrdU8) key e
  else ok false

end pedra_aeneas_prefix_kernel
