-- AUTO-GENERATED by scripts/ratchet/derive_count_annotations.py
-- RFC-0204 P1.1 — retired mirror: the Nat count-twin layer of the
-- probe ladder is MACHINE-EMITTED from the declared twin shape,
-- validated against the same parse that derives step_work (anchor
-- defs still present in the extract; emitted theorem name equals the
-- registered count row). DO NOT EDIT: regenerate with
--   python3 scripts/ratchet/derive_count_annotations.py
-- (scripts/lean_extracts.sh gates on --check before building). The
-- semantic bridges to the real extract stay HUMAN, by design, in
-- ProbeLadderBridges.lean.
import Aeneas
import ProbeOrderKernel
open Aeneas Aeneas.Std Result ControlFlow
open pedra_aeneas_probe_order_kernel

/-! ## Count twins (pure Nat, machine-emitted) -/

/-- Work twin of the covering scan: iterations while `remaining`
positions are left to scan — one step per position. -/
def covering_pos_steps : Nat → Nat
  | 0 => 0
  | remaining + 1 => 1 + covering_pos_steps remaining

/-- Work twin of the probe ladder: one fresh covering scan of `by_lo`
plus one ladder step per remaining candidate. -/
def probe_ladder_work : Nat → Nat → Nat
  | 0, _ => 0
  | candidates + 1, scan_len =>
      covering_pos_steps scan_len + 1 + probe_ladder_work candidates scan_len

/-- Scan twin bound: one iteration per remaining position, no more. -/
theorem covering_pos_steps_le : ∀ (remaining : Nat),
    covering_pos_steps remaining ≤ remaining := by
  intro remaining
  induction remaining with
  | zero => simp [covering_pos_steps]
  | succ d ih => simp only [covering_pos_steps]; omega

/-- RFC-0199 count (P0.3), machine-emitted since RFC-0204 P1.1: the
probe ladder's work twin never exceeds one `by_lo` scan plus one
ladder step per candidate — work linear in candidates × scan length,
independent of how large the deeper engine structures are. -/
theorem probe_order_covering_work_bound : ∀ (candidates scan_len : Nat),
    probe_ladder_work candidates scan_len ≤ candidates * (scan_len + 1) := by
  intro candidates scan_len
  induction candidates with
  | zero => simp [probe_ladder_work]
  | succ c ih =>
      have h := covering_pos_steps_le scan_len
      simp only [probe_ladder_work, Nat.succ_mul]
      omega
