-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_scale_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace pedra_aeneas_scale_kernel

/-- [core::convert::num::{impl core::convert::TryFrom<u128, core::num::error::TryFromIntError> for u64}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 300:12-300:64
    Name pattern: [core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::{core::convert::TryFrom<u64, u128, core::num::error::TryFromIntError>}::try_from"]
axiom U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from
  :
  Std.U128 → Result (core.result.Result Std.U64
    core.num.error.TryFromIntError)

/-- [core::num::{u64}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2516:8-2516:60
    Name pattern: [core::num::{u64}::saturating_mul]
    Visibility: public -/
@[rust_fun "core::num::{u64}::saturating_mul"]
axiom core.num.U64.saturating_mul : Std.U64 → Std.U64 → Result Std.U64

/-- [core::num::{u128}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2516:8-2516:60
    Name pattern: [core::num::{u128}::saturating_mul]
    Visibility: public -/
@[rust_fun "core::num::{u128}::saturating_mul"]
axiom core.num.U128.saturating_mul : Std.U128 → Std.U128 → Result Std.U128

/-- [core::result::{core::result::Result<T, E>}::unwrap_or]:
    Source: '/rustc/library/core/src/result.rs', lines 1590:4-1593:28
    Name pattern: [core::result::{core::result::Result<@T, @E>}::unwrap_or]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::unwrap_or"]
axiom core.result.Result.unwrap_or
  {T : Type} {E : Type} : core.result.Result T E → T → Result T

/-- [pedra_aeneas_scale_kernel::WARM_FLOOR_BYTES]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 10:0-10:48
    Visibility: public -/
@[global_simps, irreducible]
def WARM_FLOOR_BYTES : Result Std.U64 := do
  let i ← 1#u64 <<< 30#i32
  3#u64 * i

/-- [pedra_aeneas_scale_kernel::WARM_RESERVE_BYTES]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 12:0-12:44
    Visibility: public -/
@[global_simps, irreducible]
def WARM_RESERVE_BYTES : Result Std.U64 := 1#u64 <<< 30#i32

/-- [pedra_aeneas_scale_kernel::SCALE_BYTES_PER_ENTRY]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 14:0-14:43
    Visibility: public -/
@[global_simps, irreducible] def SCALE_BYTES_PER_ENTRY : Std.U64 := 245#u64

/-- [pedra_aeneas_scale_kernel::SCALE_L1_BYTES]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 16:0-16:50
    Visibility: public -/
@[global_simps, irreducible]
def SCALE_L1_BYTES : Result Std.U64 := do
  let i ← 256#u64 * 1024#u64
  i * 1024#u64

/-- [pedra_aeneas_scale_kernel::SCALE_BLOCK_BYTES]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 18:0-18:41
    Visibility: public -/
@[global_simps, irreducible] def SCALE_BLOCK_BYTES : Std.U64 := 4096#u64

/-- [pedra_aeneas_scale_kernel::SCALE_INDEX_FANOUT]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 20:0-20:39
    Visibility: public -/
@[global_simps, irreducible] def SCALE_INDEX_FANOUT : Std.U64 := 32#u64

/-- [pedra_aeneas_scale_kernel::SCALE_INDEX_SAMPLE_BYTES]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 22:0-22:45
    Visibility: public -/
@[global_simps, irreducible] def SCALE_INDEX_SAMPLE_BYTES : Std.U64 := 12#u64

/-- [pedra_aeneas_scale_kernel::SCALE_L0_BEST]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 24:0-24:33
    Visibility: public -/
@[global_simps, irreducible] def SCALE_L0_BEST : Std.U64 := 1#u64

/-- [pedra_aeneas_scale_kernel::SCALE_L0_WORST]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 26:0-26:34
    Visibility: public -/
@[global_simps, irreducible] def SCALE_L0_WORST : Std.U64 := 4#u64

/-- [pedra_aeneas_scale_kernel::SCALE_BPS]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 28:0-28:34
    Visibility: public -/
@[global_simps, irreducible] def SCALE_BPS : Std.U64 := 10000#u64

/-- [pedra_aeneas_scale_kernel::SCALE_HAPPY_COLD_HOT_BPS]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 30:0-30:48
    Visibility: public -/
@[global_simps, irreducible] def SCALE_HAPPY_COLD_HOT_BPS : Std.U64 := 2000#u64

/-- [pedra_aeneas_scale_kernel::SCALE_HAPPY_NOISY_BPS]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 32:0-32:45
    Visibility: public -/
@[global_simps, irreducible] def SCALE_HAPPY_NOISY_BPS : Std.U64 := 1000#u64

/-- [pedra_aeneas_scale_kernel::SCALE_WORST_NOISY_BPS]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 34:0-34:45
    Visibility: public -/
@[global_simps, irreducible] def SCALE_WORST_NOISY_BPS : Std.U64 := 5000#u64

/-- [pedra_aeneas_scale_kernel::SCALE_TAU_RAM_NS]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 36:0-36:40
    Visibility: public -/
@[global_simps, irreducible] def SCALE_TAU_RAM_NS : Std.U64 := 1100#u64

/-- [pedra_aeneas_scale_kernel::SCALE_TAU_DISK_NS]
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 38:0-38:42
    Visibility: public -/
@[global_simps, irreducible] def SCALE_TAU_DISK_NS : Std.U64 := 13500#u64

/-- [pedra_aeneas_scale_kernel::point_get_probes]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 42:0-44:1
    Visibility: public -/
def point_get_probes
  (levels : Std.U64) (l0_covering : Std.U64) : Result Std.U64 := do
  ok (core.num.U64.saturating_add levels l0_covering)

/-- [pedra_aeneas_scale_kernel::point_get_probes_as_is]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 48:0-50:1
    Visibility: public -/
def point_get_probes_as_is
  (n_files : Std.U64) (_levels : Std.U64) (_l0_covering : Std.U64) :
  Result Std.U64
  := do
  ok n_files

/-- [pedra_aeneas_scale_kernel::warm_cap_bytes]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 54:0-70:1
    Visibility: public -/
def warm_cap_bytes (ram_ceiling : Std.U64) : Result Std.U64 := do
  if ram_ceiling = 0#u64
  then WARM_FLOOR_BYTES
  else
    let i ← core.num.U64.saturating_mul ram_ceiling 3#u64
    let share ← i / 4#u64
    let i1 ← WARM_FLOOR_BYTES
    let cap ← if i1 >= share
                then ok i1
                else ok share
    let i2 ← WARM_RESERVE_BYTES
    let reserved ← lift (core.num.U64.saturating_sub ram_ceiling i2)
    if cap <= reserved
    then ok cap
    else ok reserved

/-- [pedra_aeneas_scale_kernel::warm_cap_bytes_as_is]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 74:0-76:1
    Visibility: public -/
def warm_cap_bytes_as_is (_ram_ceiling : Std.U64) : Result Std.U64 := do
  ok core.num.U64.MAX

/-- [pedra_aeneas_scale_kernel::probes_worst]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 80:0-82:1
    Visibility: public -/
def probes_worst (levels : Std.U64) (l0_max : Std.U64) : Result Std.U64 := do
  ok (core.num.U64.saturating_add levels l0_max)

/-- [pedra_aeneas_scale_kernel::probes_worst_as_is]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 86:0-88:1
    Visibility: public -/
def probes_worst_as_is
  (n_files : Std.U64) (_levels : Std.U64) (_l0_max : Std.U64) :
  Result Std.U64
  := do
  ok n_files

/-- [pedra_aeneas_scale_kernel::predict_get_ns]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 93:0-109:1
    Visibility: public -/
def predict_get_ns
  (probes : Std.U64) (tau_ram_ns : Std.U64) (tau_disk_ns : Std.U64)
  (hot_bps : Std.U64) (noisy_bps : Std.U64) :
  Result Std.U64
  := do
  let hot ← core.cmp.Ord.min.trait_default core.cmp.OrdU64 hot_bps SCALE_BPS
  let noisy ←
    core.cmp.Ord.min.trait_default core.cmp.OrdU64 noisy_bps 9000#u64
  let i ← core.num.U64.saturating_mul hot tau_ram_ns
  let i1 ← SCALE_BPS - hot
  let i2 ← core.num.U64.saturating_mul i1 tau_disk_ns
  let mix ← lift (core.num.U64.saturating_add i i2)
  let i3 ← lift (core.convert.num.FromU128U64.from probes)
  let i4 ← lift (core.convert.num.FromU128U64.from mix)
  let i5 ← core.num.U128.saturating_mul i3 i4
  let i6 ← lift (core.convert.num.FromU128U64.from SCALE_BPS)
  let per ← i5 / i6
  let i7 ← lift (core.convert.num.FromU128U64.from SCALE_BPS)
  let i8 ← lift (core.convert.num.FromU128U64.from noisy)
  let i9 ← i7 + i8
  let i10 ← core.num.U128.saturating_mul per i9
  let i11 ← lift (core.convert.num.FromU128U64.from SCALE_BPS)
  let taxed ← i10 / i11
  let r ← U64.Insts.CoreConvertTryFromU128TryFromIntError.try_from taxed
  core.result.Result.unwrap_or r core.num.U64.MAX

/-- [pedra_aeneas_scale_kernel::predict_get_ns_as_is]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 113:0-121:1
    Visibility: public -/
def predict_get_ns_as_is
  (n_files : Std.U64) (_tau_ram_ns : Std.U64) (tau_disk_ns : Std.U64)
  (_hot_bps : Std.U64) (_noisy_bps : Std.U64) :
  Result Std.U64
  := do
  core.num.U64.saturating_mul n_files tau_disk_ns

/-- [pedra_aeneas_scale_kernel::happy_hot_bps]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 125:0-131:1
    Visibility: public -/
def happy_hot_bps
  (store_bytes : Std.U64) (ram_bytes : Std.U64) : Result Std.U64 := do
  let i ← warm_cap_bytes ram_bytes
  if store_bytes <= i
  then ok SCALE_BPS
  else ok SCALE_HAPPY_COLD_HOT_BPS

/-- [pedra_aeneas_scale_kernel::happy_hot_bps_as_is]:
    Source: '../../../crates/pedradb-core/src/scale_kernel.rs', lines 135:0-137:1
    Visibility: public -/
def happy_hot_bps_as_is
  (_store_bytes : Std.U64) (_ram_bytes : Std.U64) : Result Std.U64 := do
  ok SCALE_BPS

end pedra_aeneas_scale_kernel
