-- AUTO-GENERATED by scripts/ratchet/derive_count_annotations.py
-- RFC-0204 P1.1 — retired mirror: the REGISTERED bound of the scale
-- side (`point_get_probes` = exact saturating levels + l0_covering)
-- is MACHINE-EMITTED from the declared twin shape, validated against
-- the same parse that derives step_work (anchor def still present in
-- the extract; emitted theorem name equals the registered count row).
-- DO NOT EDIT: regenerate with
--   python3 scripts/ratchet/derive_count_annotations.py
-- (scripts/lean_extracts.sh gates on --check before building). The
-- semantic bridge (`saturating_add_val_le`) stays HUMAN, by design, in
-- ProbeLadderBridges.lean.
import Aeneas
import ScaleKernel
import ProbeLadderBridges
open Aeneas Aeneas.Std Result
open pedra_aeneas_scale_kernel

/-- RFC-0199 count (P0.3), machine-emitted since RFC-0204 P1.1: under
the L0-covering cap invariant (`l0_covering ≤ l0_max`) and a
`levels + l0_max` that fits in u64, the probes a point get pays never
exceed `levels + l0_max` — the level-ratio shape: probes grow with
the level count, not with the file count. -/
theorem point_get_probes_le_levels_l0_max :
    ∀ (levels l0_covering l0_max : Std.U64),
      l0_covering.val ≤ l0_max.val →
      levels.val + l0_max.val ≤ 18446744073709551615 →
      ∃ v, point_get_probes levels l0_covering = ok v ∧
        v.val ≤ levels.val + l0_max.val := by
  intro levels l0_covering l0_max hcap hfit
  have h : point_get_probes levels l0_covering
      = ok (core.num.U64.saturating_add levels l0_covering) := rfl
  refine ⟨_, h, ?_⟩
  have hle := saturating_add_val_le levels l0_covering
  omega
