-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_scan_readahead_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedra_aeneas_scan_readahead_kernel

/-- [pedra_aeneas_scan_readahead_kernel::SCAN_READAHEAD_CAP_BYTES]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 24:0-24:53
    Visibility: public -/
@[global_simps, irreducible]
def SCAN_READAHEAD_CAP_BYTES : Result Std.U64 := 256#u64 * 1024#u64

/-- [pedra_aeneas_scan_readahead_kernel::MAX_WINDOW_PAIRS]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 28:0-28:35 -/
@[global_simps, irreducible] def MAX_WINDOW_PAIRS : Std.Usize := 66#usize

/-- [pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 33:0-41:1
    Visibility: public -/
structure ScanReadaheadWindow where
  offset : Std.U64
  len : Std.U64
  blocks : Std.U32

/-- [pedra_aeneas_scan_readahead_kernel::{impl core::fmt::Debug for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}::fmt]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:9-32:14
    Visibility: public -/
def ScanReadaheadWindow.Insts.CoreFmtDebug.fmt
  (self : ScanReadaheadWindow) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugU64 self.offset
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.len
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.blocks
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "ScanReadaheadWindow")
    (toStr "offset") dyn (toStr "len") dyn1 (toStr "blocks") dyn2

/-- Trait implementation: [pedra_aeneas_scan_readahead_kernel::{impl core::fmt::Debug for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:9-32:14 -/
@[reducible]
def ScanReadaheadWindow.Insts.CoreFmtDebug : core.fmt.Debug ScanReadaheadWindow
  := {
  fmt := ScanReadaheadWindow.Insts.CoreFmtDebug.fmt
}

/-- [pedra_aeneas_scan_readahead_kernel::{impl core::clone::Clone for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}::clone]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:16-32:21
    Visibility: public -/
def ScanReadaheadWindow.Insts.CoreCloneClone.clone
  (self : ScanReadaheadWindow) : Result ScanReadaheadWindow := do
  ok self

/-- Trait implementation: [pedra_aeneas_scan_readahead_kernel::{impl core::clone::Clone for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:16-32:21 -/
@[reducible]
def ScanReadaheadWindow.Insts.CoreCloneClone : core.clone.Clone
  ScanReadaheadWindow := {
  clone := ScanReadaheadWindow.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [pedra_aeneas_scan_readahead_kernel::{impl core::marker::Copy for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:23-32:27 -/
@[reducible]
def ScanReadaheadWindow.Insts.CoreMarkerCopy : core.marker.Copy
  ScanReadaheadWindow := {
  cloneInst := ScanReadaheadWindow.Insts.CoreCloneClone
}

/-- Trait implementation: [pedra_aeneas_scan_readahead_kernel::{impl core::marker::StructuralPartialEq for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:29-32:38 -/
@[reducible]
def ScanReadaheadWindow.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ScanReadaheadWindow := {
}

/-- [pedra_aeneas_scan_readahead_kernel::{impl core::cmp::PartialEq<pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow> for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}::eq]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:29-32:38
    Visibility: public -/
def ScanReadaheadWindow.Insts.CoreCmpPartialEqScanReadaheadWindow.eq
  (self : ScanReadaheadWindow) (other : ScanReadaheadWindow) :
  Result Bool
  := do
  if self.offset = other.offset
  then
    if self.len = other.len
    then ok (self.blocks = other.blocks)
    else ok false
  else ok false

/-- Trait implementation: [pedra_aeneas_scan_readahead_kernel::{impl core::cmp::PartialEq<pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow> for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:29-32:38 -/
@[reducible]
def ScanReadaheadWindow.Insts.CoreCmpPartialEqScanReadaheadWindow :
  core.cmp.PartialEq ScanReadaheadWindow ScanReadaheadWindow := {
  eq := ScanReadaheadWindow.Insts.CoreCmpPartialEqScanReadaheadWindow.eq
}

/-- [pedra_aeneas_scan_readahead_kernel::{impl core::cmp::Eq for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}::assert_fields_are_eq]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:40-32:42
    Visibility: public -/
def ScanReadaheadWindow.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ScanReadaheadWindow) : Result Unit := do
  ok ()

/-- Trait implementation: [pedra_aeneas_scan_readahead_kernel::{impl core::cmp::Eq for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:40-32:42 -/
@[reducible]
def ScanReadaheadWindow.Insts.CoreCmpEq : core.cmp.Eq ScanReadaheadWindow := {
  partialEqInst :=
    ScanReadaheadWindow.Insts.CoreCmpPartialEqScanReadaheadWindow
  assert_fields_are_eq :=
    ScanReadaheadWindow.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [pedra_aeneas_scan_readahead_kernel::{impl core::default::Default for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}::default]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:44-32:51
    Visibility: public -/
def ScanReadaheadWindow.Insts.CoreDefaultDefault.default
  : Result ScanReadaheadWindow := do
  ok
    {
      offset := (core.default.DefaultU64.default),
      len := (core.default.DefaultU64.default),
      blocks := (core.default.DefaultU32.default)
    }

/-- Trait implementation: [pedra_aeneas_scan_readahead_kernel::{impl core::default::Default for pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 32:44-32:51 -/
@[reducible]
def ScanReadaheadWindow.Insts.CoreDefaultDefault : core.default.Default
  ScanReadaheadWindow := {
  default := ScanReadaheadWindow.Insts.CoreDefaultDefault.default
}

/-- [pedra_aeneas_scan_readahead_kernel::{pedra_aeneas_scan_readahead_kernel::ScanReadaheadWindow}::NONE]
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 46:4-50:6
    Visibility: public -/
@[global_simps, irreducible]
def ScanReadaheadWindow.NONE : ScanReadaheadWindow :=
  { offset := 0#u64, len := 0#u64, blocks := 0#u32 }

/-- [pedra_aeneas_scan_readahead_kernel::scan_readahead_window]: loop body 0:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 1:0-103:5
    Visibility: public -/
@[rust_loop_body]
def scan_readahead_window_loop.body
  (blocks : Slice (Std.U64 × Std.U64)) (i : Std.U64) (i1 : Std.U32)
  (expected_off : Std.U64) (k : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.U32 × Std.U64 × Std.Usize) (Std.U64 ×
    Std.U32))
  := do
  let i2 ← SCAN_READAHEAD_CAP_BYTES
  if i < i2
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) blocks k
    match o with
    | none => ok (done (i, i1))
    | some p =>
      let (off, len) := p
      if off != expected_off
      then ok (done (i, i1))
      else
        let i3 ← lift (core.num.U64.saturating_add i len)
        if i3 > i2
        then ok (done (i, i1))
        else
          let i4 ← i + len
          let i5 ← i1 + 1#u32
          let expected_off1 ← lift (core.num.U64.saturating_add off len)
          let k1 ← k + 1#usize
          ok (cont (i4, i5, expected_off1, k1))
  else ok (done (i, i1))

/-- [pedra_aeneas_scan_readahead_kernel::scan_readahead_window]: loop 0:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 1:0-103:5
    Visibility: public -/
@[rust_loop]
def scan_readahead_window_loop
  (blocks : Slice (Std.U64 × Std.U64)) (i : Std.U64) (i1 : Std.U32)
  (expected_off : Std.U64) (k : Std.Usize) :
  Result (Std.U64 × Std.U32)
  := do
  loop
    (fun (i2, i3, expected_off1, k1) => scan_readahead_window_loop.body blocks
      i2 i3 expected_off1 k1)
    (i, i1, expected_off, k)

/-- [pedra_aeneas_scan_readahead_kernel::scan_readahead_window]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 63:0-108:1
    Visibility: public -/
def scan_readahead_window
  (blocks : Slice (Std.U64 × Std.U64)) (at1 : Std.Usize)
  (bounded_cache : Bool) :
  Result ScanReadaheadWindow
  := do
  if bounded_cache
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) blocks at1
    match o with
    | none => ok ScanReadaheadWindow.NONE
    | some p =>
      let (cur_off, cur_len) := p
      let i ← at1 + 1#usize
      let o1 ←
        core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
          Std.U64)) blocks i
      match o1 with
      | none => ok ScanReadaheadWindow.NONE
      | some p1 =>
        let (next_off, _) := p1
        let i1 ← lift (core.num.U64.saturating_add cur_off cur_len)
        if next_off != i1
        then ok ScanReadaheadWindow.NONE
        else
          let (i2, i3) ←
            scan_readahead_window_loop blocks 0#u64 0#u32 next_off i
          if i3 = 0#u32
          then ok ScanReadaheadWindow.NONE
          else ok { offset := next_off, len := i2, blocks := i3 }
  else ok ScanReadaheadWindow.NONE

/-- [pedra_aeneas_scan_readahead_kernel::scan_readahead_window_as_is]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 113:0-119:1
    Visibility: public -/
def scan_readahead_window_as_is
  (_blocks : Slice (Std.U64 × Std.U64)) (_at : Std.Usize)
  (_bounded_cache : Bool) :
  Result ScanReadaheadWindow
  := do
  ok ScanReadaheadWindow.NONE

/-- [pedra_aeneas_scan_readahead_kernel::scan_readahead_bounded]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 125:0-127:1
    Visibility: public -/
def scan_readahead_bounded
  (sst_bytes : Std.U64) (warm_cap : Std.U64) : Result Bool := do
  ok (sst_bytes > warm_cap)

/-- [pedra_aeneas_scan_readahead_kernel::scan_readahead_pair_budget]:
    Source: '../../../crates/pedradb-core/src/scan_readahead_kernel.rs', lines 132:0-134:1
    Visibility: public -/
def scan_readahead_pair_budget : Result Std.Usize := do
  ok MAX_WINDOW_PAIRS

end pedra_aeneas_scan_readahead_kernel
