-- AUTO-GENERATED by scripts/ratchet/derive_count_annotations.py
-- RFC-0204 P1.1 — retired mirror: the Nat count-twin layer of the
-- scan decision is MACHINE-EMITTED from the declared twin shape,
-- validated against the same parse that derives step_work (anchor
-- def still present in the extract; emitted theorem name equals the
-- registered count row). DO NOT EDIT: regenerate with
--   python3 scripts/ratchet/derive_count_annotations.py
-- (scripts/lean_extracts.sh gates on --check before building). The
-- semantic bridges to the real extract stay HUMAN, by design, in
-- ScanDecisionBridges.lean.
import Aeneas
import ScanKernel
open Aeneas Aeneas.Std Result
open pedra_aeneas_scan_kernel

/-! ## Count twins (pure Nat, machine-emitted) -/

/-- Work twin of the tombstone walk: one check per recorded
tombstone. -/
def scan_tomb_steps : Nat → Nat
  | 0 => 0
  | t + 1 => 1 + scan_tomb_steps t

/-- Tombstone walk bound: one step per tombstone, no more. -/
theorem scan_tomb_steps_le : ∀ (t : Nat), scan_tomb_steps t ≤ t := by
  intro t
  induction t with
  | zero => simp [scan_tomb_steps]
  | succ d ih => simp only [scan_tomb_steps]; omega

/-- A file the scan consults: whether its bounds overlap the window,
and how many tombstones it records. -/
structure ScanFile where
  overlap : Bool
  tombs : Nat

/-- Work twin of `scan_reads_file` for one file: one decision, plus
the tombstone walk only when the overlap does not short-circuit. -/
def scan_file_steps (f : ScanFile) : Nat :=
  match f.overlap with
  | true => 1
  | false => 1 + scan_tomb_steps f.tombs

/-- Work twin of the scan over the candidate file list. -/
def scan_files_steps : List ScanFile → Nat
  | [] => 0
  | f :: fs => scan_file_steps f + scan_files_steps fs

/-- Total tombstones recorded across the candidate list. -/
def scan_tomb_total : List ScanFile → Nat
  | [] => 0
  | f :: fs => f.tombs + scan_tomb_total fs

/-- RFC-0199 count (P1.4), machine-emitted since RFC-0204 P1.1: the
scan decision work over a candidate list never exceeds one decision
per file plus one check per recorded tombstone — linear in files +
tombstones, independent of file contents. -/
theorem scan_decision_work_bound : ∀ (files : List ScanFile),
    scan_files_steps files ≤ files.length + scan_tomb_total files := by
  intro files
  induction files with
  | nil => simp [scan_files_steps, scan_tomb_total]
  | cons f fs ih =>
      have hle := scan_tomb_steps_le f.tombs
      simp only [scan_files_steps, scan_tomb_total, List.length_cons, scan_file_steps]
      split <;> omega
