-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pedra_aeneas_store_commit_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pedra_aeneas_store_commit_kernel

/-- [pedra_aeneas_store_commit_kernel::recover_commit]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 13:0-15:1
    Visibility: public -/
def recover_commit
  (loaded_commit : Std.U64) (log_last : Std.U64) : Result Std.U64 := do
  core.cmp.Ord.min.trait_default core.cmp.OrdU64 loaded_commit log_last

/-- [pedra_aeneas_store_commit_kernel::recover_last_applied]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 19:0-21:1
    Visibility: public -/
def recover_last_applied : Result Std.U64 := do
  ok 0#u64

/-- [pedra_aeneas_store_commit_kernel::may_commit_at]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 25:0-27:1
    Visibility: public -/
def may_commit_at
  (index_term : Std.U64) (current_term : Std.U64) (has_majority : Bool) :
  Result Bool
  := do
  if has_majority
  then ok (index_term = current_term)
  else ok false

/-- [pedra_aeneas_store_commit_kernel::propose_ack_ok]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 31:0-33:1
    Visibility: public -/
def propose_ack_ok
  (index : Std.U64) (commit_index : Std.U64) : Result Bool := do
  ok (commit_index >= index)

/-- [pedra_aeneas_store_commit_kernel::recover_commit_as_is]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 37:0-39:1
    Visibility: public -/
def recover_commit_as_is
  (_loaded_commit : Std.U64) (log_last : Std.U64) : Result Std.U64 := do
  ok log_last

/-- [pedra_aeneas_store_commit_kernel::recover_last_applied_as_is]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 43:0-45:1
    Visibility: public -/
def recover_last_applied_as_is (log_last : Std.U64) : Result Std.U64 := do
  ok log_last

/-- [pedra_aeneas_store_commit_kernel::may_commit_at_as_is]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 49:0-51:1
    Visibility: public -/
def may_commit_at_as_is
  (_index_term : Std.U64) (_current_term : Std.U64) (has_majority : Bool) :
  Result Bool
  := do
  ok has_majority

/-- [pedra_aeneas_store_commit_kernel::propose_ack_ok_as_is]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 55:0-57:1
    Visibility: public -/
def propose_ack_ok_as_is
  (_index : Std.U64) (_commit_index : Std.U64) : Result Bool := do
  ok true

/-- [pedra_aeneas_store_commit_kernel::should_advance_commit]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 61:0-63:1
    Visibility: public -/
def should_advance_commit
  (new_idx : Std.U64) (current : Std.U64) : Result Bool := do
  ok (new_idx > current)

/-- [pedra_aeneas_store_commit_kernel::should_advance_commit_as_is]:
    Source: '../../../crates/pedradb-store/src/commit_kernel.rs', lines 67:0-69:1
    Visibility: public -/
def should_advance_commit_as_is
  (_new_idx : Std.U64) (_current : Std.U64) : Result Bool := do
  ok true

end pedra_aeneas_store_commit_kernel
